### PR TITLE
Special case C _Bool by treating it like a Rust bool instead of gboolean

### PR DESCRIPTION
**Pull request by sdroege**
Fixes https://github.com/gtk-rs/gir/issues/1205

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Nice, thanks for looking into it ! Mind submitting a PR against gtk-rs-core to see how the re-generated graphene looks like?

**Comment by sdroege** [comment]
On it

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/282. Also comes with a test that fails before and succeeds after.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
