### PR TITLE
Fix enums from_glib unsafety, store unknown value

### PR DESCRIPTION
**Pull request by EPashkin**
Part of #123

cc @GuillaumeGomez, @sdroege 

Make enums look as https://github.com/gtk-rs/gir/issues/123#issuecomment-309222862

### CODE REVIEW

**Comment by sdroege** [comment]
Looks good to me 👍

**Comment by EPashkin** [comment]
@GuillaumeGomez Please, take look

**Comment by GuillaumeGomez** [comment]
Looks good to me too!

**Comment by EPashkin** [comment]
Checked all PRs linked to this, CI passed too. 👍 for merge.

**Comment by GuillaumeGomez** [comment]
Ok, let's start a merge fest!

**Comment by GuillaumeGomez** [comment]
All merged. Thanks to both of you! ;)

**Pull request merged**
