### PR TITLE
Use a newtype wrapper for the signal handler IDs

### PR DESCRIPTION
**Pull request by sdroege**
https://github.com/gtk-rs/glib/issues/229

### CODE REVIEW

**Comment by EPashkin** [comment]
Sorry, I forgot about this PR.

**Comment by EPashkin** [comment]
Note: now regen on gtk produced many `ERROR:gir::analysis::trampoline_parameters: Wrong conversion_type for borrow transformation Borrow`, but code seems good.

**Comment by sdroege** [comment]
Do you understand why that warning happens and exists?

Will send regens in a bit, lunch first

**Comment by EPashkin** [comment]
It was manually changed conversion type for `TransformationType::Borrow` when `ConversionType::Pointer` passed to `ConversionType::Borrow`,
As you changed passed to `ConversionType::Borrow` it think that you used unsupported type and nags.
I fix it.

**Pull request merged**
