### PR TITLE
Trampoline namespaces

### LINKED ISSUE #239: Signals with parameters from other modules
Part of #199
Some signals contains parameters from other modules:
CellArea: add-editable
CellRendererAccel: accel-edited
TextBuffer: insert-pixbuf
Widget: draw, screen-changed
Problem that current generator use `codegen\sys\ffi_type.rs` for generate trampoline parameters,
so we get wrong module.
Ex.
```
fn connect_add_editable<F: Fn(&Self, &CellRenderer, &CellEditable, &cairo::RectangleInt, &str) + 'static>(&self, f: F) -> u64 {
    unsafe {
        let f: Box_<Box_<Fn(&Self, &CellRenderer, &CellEditable, &cairo::RectangleInt, &str) + 'static>> = Box_::new(Box_::new(f));
        connect(self.to_glib_none().0, "add-editable",
            transmute(add_editable_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
    }
}
unsafe extern "C" fn add_editable_trampoline<T>(this: *mut GtkCellArea, renderer: *mut GtkCellRenderer, editable: *mut GtkCellEditable, cell_area: *mut cairo::cairo_rectangle_int_t, path: *mut c_char, f: gpointer)
where T: IsA<CellArea> {
    callback_guard!();
    let f: &Box_<Fn(&T, &CellRenderer, &CellEditable, &cairo::RectangleInt, &str) + 'static> = transmute(f);
    f(&CellArea::from_glib_none(this).downcast_unchecked(), &from_glib_none(renderer), &from_glib_none(editable), &from_glib_none(cell_area), &String::from_glib_none(path))
}

```

For `add_editable_trampoline` must be `cell_area: *mut cairo::cairo_ffi_rectangle_int_t`
Also trampoline first parameter better be `this: *mut ffi::GtkCellArea` (all ffi classes must be with module name)

### PR DESCRIPTION
**Pull request by EPashkin**
Closes #239

### CODE REVIEW

**Comment by EPashkin** [comment]
Commit "Use ffi_type in used_ffi_types" use `libc` types in trampolines with prefix, may be better remove it?
```
--- a/src/auto/dialog.rs
+++ b/src/auto/dialog.rs
@@ -13,7 +13,7 @@ use glib::object::IsA;
 use glib::signal::connect;
 use glib::translate::*;
 use glib_ffi::gpointer;
-use libc::c_int;
+use libc;
 use std::boxed::Box as Box_;
 use std::mem::transmute;
 
@@ -177,7 +177,7 @@ where T: IsA<Dialog> {
     f(&Dialog::from_glib_none(this).downcast_unchecked())
 }
 
-unsafe extern "C" fn response_trampoline<T>(this: *mut ffi::GtkDialog, response_id: c_int, f: gpointer)
+unsafe extern "C" fn response_trampoline<T>(this: *mut ffi::GtkDialog, response_id: libc::c_int, f: gpointer)
 where T: IsA<Dialog> {
     callback_guard!();
     let f: &Box_<Fn(&T, i32) + 'static> = transmute(f);
```

**Comment by gkoz** [comment]
> libc types in trampolines with prefix

Both ways seem fine to me.

**Comment by gkoz** [comment]
From looking at the build error in `add-editable` we just need a `FromGlibPtr` implementation for `RectangleInt`?

**Comment by EPashkin** [comment]
Updated last commit to use `f: glib_ffi::gpointer`

**Pull request merged**
