### PR TITLE
Replace all try! with ?

### PR DESCRIPTION
**Pull request by kornelski**
Done with https://users.rust-lang.org/t/automatically-replace-all-try-with/16873

### CODE REVIEW

**Comment by EPashkin** [comment]
@kornelski Thanks for fix and method.

@GuillaumeGomez @sdroege @tmiasko Merging this not cause too much problem with your changes?

**Comment by GuillaumeGomez** [comment]
It might cause conflicts with my current PR but besides that it doesn't seem to change any return type so that shouldn't be too dramatic...

**Comment by GuillaumeGomez** [comment]
My PR is already big enough to avoid such changes. I prefer PR to focus on one thing. It's already hard enough to review. :p

**Comment by sdroege** [comment]
> @GuillaumeGomez @sdroege @tmiasko Merging this not cause too much problem with your changes?

We'll see but I can update my changes, no worries :)

**Pull request closed without merging**
