### PR TITLE
Class builder includes properties of  implemented interfaces

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gtk/issues/892

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by EPashkin** [comment]
Updated to use parent configs

**Comment by GuillaumeGomez** [comment]
Still :+1:

**Comment by EPashkin** [comment]
Ok, let finish this batch

**Pull request merged**
