### PR TITLE
Update to bitflags 2.2

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/1052

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by sdroege** [comment]
Thanks for the review, will merge this once someone took care of https://github.com/gtk-rs/gtk-rs-core/pull/1052#discussion_r1223919994 (which involves more manual work than I have time for right now).

**Comment by bilelmoussaoui** [comment]
I would love if we could merge this simultaneously with https://github.com/gtk-rs/gir/pull/1469 so we can drop the bitflags direct dependency from all the crates except glib.

**Comment by sdroege** [comment]
Sounds good to me

**Pull request merged**
