### PR TITLE
docs: Handle gi-docgen namespaces when looking for types to link

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Otherwise causes issue when looking for GtkApplication and you end up with a GApplication link

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
not tested yet, doing that right now

**Comment by bilelmoussaoui** [comment]
Before: 
image

After
image

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks!

**Comment by MarijnS95** [comment]
@bilelmoussaoui in the second screenshot the `core::gtk::Application` link broke, is that the intended change of this PR?

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui in the second screenshot the `core::gtk::Application` link broke (but `Value::init()` got fixed), is that the intended change of this PR?

Because I built the docs locally with `--no-deps`, it needs the ` extern-html-root-url` to work but also shows that it is actually using gtk::Application instead of adw::Application there

**Pull request merged**
