### PR TITLE
WIP: Support string type override

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/592
All works fine, but need last attempt to remove ugly code in src/analysis/out_parameters.rs

cc @GuillaumeGomez

### CODE REVIEW

**Comment by EPashkin** [comment]
@sdroege You was right: need only one options to configure switch string between `String`, `PathBuf` and `OsString`

**Comment by GuillaumeGomez** [comment]
Looks good to me. That's a great change! :)

**Comment by sdroege** [comment]
Same, thanks :)

**Comment by EPashkin** [comment]
Then I merge and update PR for glib, prepare PR for gio

**Pull request merged**
