### PR TITLE
codegen: generate NONE constants as associated constants

### PR DESCRIPTION
**Pull request by fengalin**
So that we can use `Pad::NONE` instead of crate global `NONE_PAD`.

Fixes https://github.com/gtk-rs/gir/issues/1252

### CODE REVIEW

**Comment by fengalin** [comment]
> That's pretty great, but wasn't there already an existing impl block where this constant could be moved into?

I don't think so. The main `impl` block is usually behind a `glib` `macro` and the `NONE` constant generation depends on a condition known to `gir`. Others `impl` blocks generation depend on the generated `struct`. See [buffer_pool](https://gitlab.freedesktop.org/fengalin/gstreamer-rs/-/blob/none-associated-const/gstreamer/src/auto/buffer_pool.rs) as an example.

Besides, I like to separate `impl` blocks by purposes. But I'd be happy to merge with another block if you find a suitable candidate :)

**Comment by fengalin** [comment]
AFAICT, CI failures are expected as it requires the updates to `gtk-rs-core` and co.

**Comment by MarijnS95** [comment]
It may have been bitflags/enums that always have an `impl` block (which this `const` could be conditionally added to), sorry for the confusion!

**Comment by fengalin** [comment]
NP. I applied your suggestion to manually changed code.

**Review by sdroege — APPROVED** [review]

**Comment by sdroege** [comment]
@GuillaumeGomez @bilelmoussaoui Ok with you too?

**Comment by fengalin** [comment]
Please ping me before merging so I can update the dependent PRs immediately.

**Review by bilelmoussaoui — APPROVED** [review]

**Pull request merged**
