### PR TITLE
Fix unused bounds in futures

### PR DESCRIPTION
**Pull request by EPashkin**
See https://github.com/gtk-rs/gio/pull/179#pullrequestreview-192970234

cc @sdroege, @GuillaumeGomez

### CODE REVIEW

**Comment by EPashkin** [comment]
Added https://github.com/gtk-rs/gio/pull/180 with results,
Other affected gtk, crates sourceview
Also changed commented functions gdk-pixbuf

**Comment by sdroege** [comment]
Hrm, thanks! I didn't notice this one

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by sdroege** [comment]
@EPashkin you also send gtk/sourceview/gdk-pixbuf PRs?

**Comment by EPashkin** [comment]
@sdroege Yes

**Comment by EPashkin** [comment]
.. with exception of gdk-pixbuf, only commented function changed here.

**Pull request merged**
