### PR TITLE
Fall back for "type-name" for objects

### LINKED ISSUE #835: polkit: Attribute `type` on element <interface> is required.
I'm attempted to create bindings for Polkit, and figuring out how Gir works in the process. I'm currently hitting this error:

```
gir/target/bin/gir -c Gir.toml
GirXml: gir-files/Polkit-1.0.gir at line 1741:4: Attribute `type` on element <interface> is required.
```

```toml
[options]
girs_dir = "gir-files"
library = "Polkit"
version = "1.0"
min_cfg_version = "1.0"
target_path = "."
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
	"Polkit.ActionDescription",
	"Polkit.Authority",
	"Polkit.AuthorizationResult",
	"Polkit.Details",
	"Polkit.Error",
	"Polkit.Identity",
	"Polkit.Permission",
	"Polkit.SystemBusName",
	"Polkit.Subject",
	"Polkit.TemporaryAuthorization",
	"Polkit.UnixGroup",
	"Polkit.UnixNetgroup",
	"Polkit.UnixProcess",
	"Polkit.UnixSession",
	"Polkit.UnixUser"
]

ignore = []
```

### PR DESCRIPTION
**Pull request by EPashkin**
Fix #835

@mmstick Does this fix issue?

cc  @GuillaumeGomez , @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by sdroege** [comment]
Is that a new version of gobject-introspection that only adds one instead of the other or what changed here? Are we sure it's always exactly what we want?

**Comment by EPashkin** [comment]
@sdroege Not sure why it not written, by code it was in <class> too.
At minimum last [schema](https://gitlab.gnome.org/GNOME/gobject-introspection/blob/master/docs/gir-1.2.rnc#L123) says that "c:type" now optional while "glib:type-name" is not.
Maybe this function need be changed, or removed in favor or reading second

**Comment by sdroege** [comment]
Makes sense I guess

**Comment by EPashkin** [comment]
Checked schema:
* Record doesn't have glib:type-name,
* Union has both optional,
* Bitfield and Enum have required c:type and optional glib:type-name.

So I only removed record changes, and all others still use `read_object_c_type` as it cover their cases.

**Comment by sdroege** [comment]
:+1:

**Comment by mmstick** [comment]
Seems to fix the issue. It no longer fails. I just get this now:

```
gir/target/bin/gir -c Gir.toml
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_get_finish has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_get_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_authentication_agent_response_finish has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_authentication_agent_response_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_check_authorization_finish has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_check_authorization_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_enumerate_actions_finish has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_enumerate_actions_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_enumerate_temporary_authorizations_finish has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_enumerate_temporary_authorizations_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_register_authentication_agent_finish has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_register_authentication_agent_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_register_authentication_agent_with_options_finish has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_register_authentication_agent_with_options_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_revoke_temporary_authorization_by_id_finish has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_revoke_temporary_authorization_by_id_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_revoke_temporary_authorizations_finish has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_revoke_temporary_authorizations_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_unregister_authentication_agent_finish has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_authority_unregister_authentication_agent_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_identity_from_string has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_permission_new_finish has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_permission_new_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_subject_from_string has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_subject_exists_finish has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_subject_exists_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_system_bus_name_get_process_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_system_bus_name_get_user_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_unix_group_new_for_name has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_unix_process_get_owner has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_unix_session_new_for_process_finish has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_unix_session_new_for_process_sync has unsupported outs
[2019-09-05T17:02:35Z WARN  libgir::analysis::functions] Function polkit_unix_user_new_for_name has unsupported outs
```

**Comment by EPashkin** [comment]
@mmstick Thanks for confirmation.
`Unsupported out` mostly for out arrays and pointers and currently can be written only manually.
I can't find correct issue (#596 and #594 IMHO is not about this) so can you fill issue with list of problem functions and links to your repos?
We have some of it too:
`gdk_device_get_history`, `g_file_info_get_attribute_data`, `g_main_context_query`, `pango_layout_get_log_attrs`, `pango_tab_array_get_tabs`, `gtk_buildable_custom_tag_start`

**Pull request merged**
