### PR TITLE
Correctly cast pointers in property getters/setters if no trait is to…

### PR DESCRIPTION
**Pull request by sdroege**
… be generated

Needed for GStreamer but didn't appear anywhere in the gtk-rs crates

### CODE REVIEW

**Comment by EPashkin** [comment]
@sdroege Thanks.
PR don't do any changes in gtk-rs, I just waiting CI.

**Comment by sdroege** [comment]
It's not complete yet, `ObjectType` import is missing sometimes. Fixing :)

**Comment by sdroege** [comment]
now it's good

**Comment by EPashkin** [comment]
Thanks

**Pull request merged**
