### PR TITLE
Handle glib::Pid conversions specifically

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I updated https://github.com/gtk-rs/gio/pull/230 so you can see this change too.

**Comment by sdroege** [comment]
Generated code looks good to me

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks, I merge this as is. but, please, don't forget to fix it in `glib::spawn_async` too

**Comment by GuillaumeGomez** [comment]
@EPashkin I'll create an issue just in case.

**Pull request merged**
