### PR TITLE
Use inner c:type for arrays with fixed size in sys mode

### PR DESCRIPTION
**Pull request by EPashkin**
Part of #648, #652

Only change sys generation

@alatiera please check this version on gstreamer-sys

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Code looks good to me. Do you have an example of the change in a sys library? Just one function is enough. :)

**Comment by EPashkin** [comment]
In your sys for #652
```diff
--- a/gtk-sys/src/lib.rs
+++ b/gtk-sys/src/lib.rs
@@ -1207,7 +1207,7 @@ impl ::std::fmt::Debug for GtkBindingArg_d {
 #[repr(C)]
 #[derive(Copy, Clone)]
 pub union GtkTextAppearance_u1 {
-    pub rgba: [gdk::GdkRGBA; 2],
+    pub rgba: [*mut gdk::GdkRGBA; 2],
     pub padding: [c_uint; 4],
 }
 
@@ -11819,7 +11819,7 @@ impl ::std::fmt::Debug for GtkRangeAccessible {
 pub struct GtkRcStyle {
     pub parent_instance: gobject::GObject,
     pub name: *mut c_char,
-    pub bg_pixmap_name: [c_char; 5],
+    pub bg_pixmap_name: [*mut c_char; 5],
     pub font_desc: *mut pango::PangoFontDescription,
     pub color_flags: [GtkRcFlags; 5],
     pub fg: [gdk::GdkColor; 5],
```

in gstreamer i checked only 2 parts:
```diff
--- a/gstreamer-mpegts-sys/src/lib.rs
+++ b/gstreamer-mpegts-sys/src/lib.rs
@@ -1238,7 +1238,7 @@ impl ::std::fmt::Debug for GstMpegtsExtendedEventItem {
 #[derive(Copy, Clone)]
 pub struct GstMpegtsISO639LanguageDescriptor {
     pub nb_language: c_uint,
-    pub language: [c_char; 64],
+    pub language: [*mut c_char; 64],
     pub audio_type: [GstMpegtsIso639AudioType; 64],
 }
```
```diff
--- a/gstreamer-sdp-sys/src/lib.rs
+++ b/gstreamer-sdp-sys/src/lib.rs
@@ -230,7 +230,7 @@ pub struct GstMIKEYPayloadKeyData {
     pub salt_data: *mut u8,
     pub kv_type: GstMIKEYKVType,
     pub kv_len: [u8; 2],
-    pub kv_data: [u8; 2],
+    pub kv_data: [*mut u8; 2],
 }
 
 impl ::std::fmt::Debug for GstMIKEYPayloadKeyData {
```

**Comment by sdroege** [comment]
This fixes two things and breaks another.

Fixes:
```diff
@@ -1238,7 +1238,7 @@ impl ::std::fmt::Debug for GstMpegtsExtendedEventItem {
 #[derive(Copy, Clone)]
 pub struct GstMpegtsISO639LanguageDescriptor {
     pub nb_language: c_uint,
-    pub language: [c_char; 64],
+    pub language: [*mut c_char; 64],
     pub audio_type: [GstMpegtsIso639AudioType; 64],
 }
 
@@ -230,7 +230,7 @@ pub struct GstMIKEYPayloadKeyData {
     pub salt_data: *mut u8,
     pub kv_type: GstMIKEYKVType,
     pub kv_len: [u8; 2],
-    pub kv_data: [u8; 2],
+    pub kv_data: [*mut u8; 2],
 }
 
 impl ::std::fmt::Debug for GstMIKEYPayloadKeyData {
```

Breaks:

```diff
@@ -249,8 +249,8 @@ pub const GST_AUDIO_RESAMPLER_FLAG_VARIABLE_RATE: GstAudioResamplerFlags = 4;
 // Callbacks
 pub type GstAudioBaseSinkCustomSlavingCallback = Option<unsafe extern "C" fn(*mut GstAudioBaseSink, gst::GstClockTime, gst::GstClock
Time, *mut gst::GstClockTimeDiff, GstAudioBaseSinkDiscontReason, gpointer)>;
 pub type GstAudioClockGetTimeFunc = Option<unsafe extern "C" fn(*mut gst::GstClock, gpointer) -> gst::GstClockTime>;
-pub type GstAudioFormatPack = Option<unsafe extern "C" fn(*const GstAudioFormatInfo, GstAudioPackFlags, gpointer, gpointer, c_int)>;
-pub type GstAudioFormatUnpack = Option<unsafe extern "C" fn(*const GstAudioFormatInfo, GstAudioPackFlags, gpointer, gpointer, c_int)
>;
+pub type GstAudioFormatPack = Option<unsafe extern "C" fn(*const GstAudioFormatInfo, GstAudioPackFlags, u8, gpointer, c_int)>;
+pub type GstAudioFormatUnpack = Option<unsafe extern "C" fn(*const GstAudioFormatInfo, GstAudioPackFlags, gpointer, u8, c_int)>;
 pub type GstAudioRingBufferCallback = Option<unsafe extern "C" fn(*mut GstAudioRingBuffer, *mut u8, c_uint, gpointer)>;
 
 // Records
```

**Comment by sdroege** [comment]
CC @russel this is fixing one of the MPEG-TS problems you were running into

**Comment by sdroege** [comment]
Oh the `GstAudioFormatPack/Unpack` comes from an earlier commit already. This PR is fine! Will create a new issue for that one

**Comment by sdroege** [comment]
> I regenerated everything. Trying to find the commit now that broke it :)

In any case, merge this one.

I think it's a broken .gir file that breaks the other array...

**Comment by sdroege** [comment]
It is: https://github.com/gtk-rs/gir/issues/654

**Comment by EPashkin** [comment]
I waiting for @GuillaumeGomez approval just in case.

**Comment by GuillaumeGomez** [comment]
All good for me!

**Comment by EPashkin** [comment]
Then I merge
@sdroege, @GuillaumeGomez Thanks for review

**Pull request merged**
