### PR TITLE
Add support for gsize/gssize by using usize/isize

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
Note that this exposes some API in GTK (e.g. `gtk_recent_chooser_get_uris`) which previously was not exposed, but those need https://github.com/gtk-rs/gir/issues/376 properly fixed before being correct.

**Comment by EPashkin** [comment]
Thanks.

Many function generated by GLib-2.0.gir is failing (Ex. `g_convert_with_fallback` don't have `out`) and need ignored.
Gio also affected.

**Comment by sdroege** [comment]
Yes, those are also on my list. It's 2-3 separate issues :)

**Comment by EPashkin** [comment]
@sdroege you planing apply this to `glib` in near time?
It currently "block" checking all other gir PR's
If in plan only ignoring not compiling function then I can do it today.

**Comment by sdroege** [comment]
Probably won't get to this specific one today though, but it's high up in my list next week

**Pull request merged**
