### PR TITLE
Enums primary detects error domain by function "quark"

### PR DESCRIPTION
**Pull request by EPashkin**
For https://github.com/gtk-rs/gtk/issues/381#issuecomment-247492968

### CODE REVIEW

**Comment by gkoz** [comment]
I was hoping we could automate it: add `quark` to "special" functions then if there's a `quark` function and `glib:error-domain` is present set its value to that function's name.

**Comment by EPashkin** [comment]
I try do it

**Comment by EPashkin** [comment]
@gkoz thanks for idea, it works fine

**Comment by gkoz** [comment]
Huh, it turned out more elegant than I expected. Thanks!

**Pull request merged**
