### PR TITLE
Update to bitflags 0.8

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by EPashkin** [comment]
It not give any problem that was in #296 from rustc side.
cc @GuillaumeGomez

**Comment by sdroege** [comment]
Ah, I should've checked existing pull request first. Not sure what problem there was before, but this one seems to working just fine

**Comment by EPashkin** [comment]
Its normal my PR was a long ago.
I tend to merge this.

**Comment by GuillaumeGomez** [comment]
Good for me, thanks!

**Pull request merged**
