### PR TITLE
Fix renamed trait docs

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/500

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Ah finally. Thanks!

:+1:

**Comment by EPashkin** [comment]
@GuillaumeGomez To be sure that PR done right, can you update docs on gtk-rs, when you have time?

**Comment by GuillaumeGomez** [comment]
Sure. Please remind me saturday if I forget.

**Comment by EPashkin** [comment]
As https://github.com/gtk-rs/docs/pull/13 merged and result seems good.
I merge this too.

**Pull request merged**
