### PR TITLE
Create fewer boxes for closures

### PR DESCRIPTION
**Pull request by sdroege**
See the individual commits for explanations.

Needs some manual code updated too, which I'll do after the regens are all through.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by sdroege** [comment]
Let's get this in together with the callback generation fixes. It's small enough and we can regenerate all things at once.

**Comment by EPashkin** [comment]
@sdroege Thanks, I merge it.
Agree, that result better included in closures regen.
Note: don't forget to fix signal::destroy_closure

**Comment by EPashkin** [comment]
listbox_model example now fails on close edit dialog

**Comment by sdroege** [comment]
>  Note: don't forget to fix signal::destroy_closure

Ah that sucks. We need to make that one generic too. Let me fix all that, sorry

**Comment by GuillaumeGomez** [comment]
I wait. But I hope you can feel the pressure now. :stuck_out_tongue:

**Comment by EPashkin** [comment]
@sdroege Thanks, now listbox_model works fine.

**Pull request merged**
