### PR TITLE
Remove adding callback_guard

### PR DESCRIPTION
**Pull request by EPashkin**
Stable rust v1.27.0 landed, so I start removing callback guard

Part of https://github.com/gtk-rs/glib/pull/250 and https://github.com/gtk-rs/glib/issues/304
Previous attempt:  https://github.com/gtk-rs/gir/pull/547

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:tada:

**Comment by sdroege** [comment]
Are we sure 1.27 actually has the required changes? I lost track

**Comment by EPashkin** [comment]
You said it have: https://github.com/gtk-rs/glib/pull/250#issuecomment-369153754

**Comment by sdroege** [comment]
I'll double check tonight, I can't remember :) or one of you double checks

**Comment by EPashkin** [comment]
@sdroege Next log after adding `panic!("test");` to bigbutton_click in builder_basics.rs
```
     Running `D:\eap\rust\0\./target\debug\builder_basics.exe`
thread 'main' panicked at 'test', src\bin\builder_basics.rs:55:1
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at libstd\sys\windows\backtrace/mod.rs:65
   1: std::sys_common::backtrace::print
             at libstd\sys_common/backtrace.rs:71
             at libstd\sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::begin_panic
             at C:\projects\rust\src\libstd/panicking.rs:445
   6: builder_basics::example::build_ui::{{closure}}
             at src\bin/builder_basics.rs:55
   7: core::ops::function::impls::<impl core::ops::function::Fn<A> for &'a F>::call
             at C:\projects\rust\src\libcore\ops/function.rs:232
   8: gtk::auto::button::clicked_trampoline
             at D:/eap/rust/0/gtk\src\auto/button.rs:443
   9: unit_addrs_search
  10: unit_addrs_search
  11: unit_addrs_search
  12: unit_addrs_search
  13: unit_addrs_search
  14: unit_addrs_search
  15: unit_addrs_search
  16: unit_addrs_search
  17: unit_addrs_search
  18: unit_addrs_search
  19: unit_addrs_search
  20: unit_addrs_search
  21: unit_addrs_search
  22: unit_addrs_search
  23: unit_addrs_search
  24: unit_addrs_search
  25: unit_addrs_search
  26: unit_addrs_search
  27: unit_addrs_search
  28: unit_addrs_search
  29: unit_addrs_search
  30: unit_addrs_search
  31: unit_addrs_search
  32: unit_addrs_search
  33: unit_addrs_search
  34: unit_addrs_search
  35: unit_addrs_search
  36: unit_addrs_search
  37: unit_addrs_search
  38: unit_addrs_search
  39: unit_addrs_search
  40: unit_addrs_search
  41: unit_addrs_search
  42: unit_addrs_search
  43: unit_addrs_search
  44: unit_addrs_search
  45: unit_addrs_search
  46: unit_addrs_search
  47: <O as gio::application::ApplicationExtManual>::run
             at D:/eap/rust/0/gio\src/application.rs:23
  48: builder_basics::example::main
             at src\bin/builder_basics.rs:73
  49: builder_basics::main
             at src\bin/builder_basics.rs:79
  50: std::rt::lang_start::{{closure}}
             at C:\projects\rust\src\libstd/rt.rs:74
  51: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  52: _rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  53: std::panic::catch_unwind
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
  54: std::rt::lang_start_internal
             at libstd/rt.rs:58
  55: std::rt::lang_start
             at C:\projects\rust\src\libstd/rt.rs:74
  56: main
  57: _tmainCRTStartup
  58: mainCRTStartup
  59: unit_addrs_search
  60: unit_addrs_search
error: process didn't exit successfully: `D:\eap\rust\0\./target\debug\builder_basics.exe` (exit code: 101)

```

**Comment by sdroege** [comment]
I guess that's fine then :)

**Pull request merged**
