### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Follow-up of https://github.com/gtk-rs/gtk-rs/pull/18

### CODE REVIEW

**Comment by sdroege** [comment]
@GuillaumeGomez What do we do about Windows? Disable that for now until someone figures out why it's completely useless? This might just need something like `pacman update` in the beginning, not sure.

**Comment by GuillaumeGomez** [comment]
I'm investigating. I think we should already merge this PR and I'll continue to look on another branch since we at least fixed linux build. What do you think?

**Comment by sdroege** [comment]
Works for me

**Comment by ids1024** [comment]
I'm not sure what the best practices on Github Actions are, but using `pacman -Syu` in place of `pacman -S` should update the package database and install updates (just `pacman -Sy` will only do the first; not sure if that is likely to cause issues in practice).

**Comment by GuillaumeGomez** [comment]
@ids1024 None of us know much about Windows so any lead is good. I'll try what you suggested. :)

**Comment by ids1024** [comment]
> None of us know much about Windows so any lead is good. 

I don't know much about Windows either, but `pacman` is the Arch Linux package manger, which msys2 apparently decided to use.

**Pull request merged**
