### PR TITLE
Generate child properties

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gtk/issues/392
WIP as support only `gboolean` and `gint`

### CODE REVIEW

**Comment by EPashkin** [comment]
Seems ready to merge

**Comment by EPashkin** [comment]
Added tests for child config

**Comment by EPashkin** [comment]
@GuillaumeGomez, ready for merge.
Only last untested is object/interface properties due deprecation of `GtkAssistant`'s pixbufs.
PS. Enum and strings tested with https://github.com/EPashkin/examples/tree/assistant

**Comment by GuillaumeGomez** [comment]
Ok, so I looked the code and it seems good. So once more, I'll let you handle the merge. Thanks for your work!

**Pull request merged**
