### PR TITLE
Implement generation of emitter functions for action signals

### PR DESCRIPTION
**Pull request by sdroege**
This is all WIP for now, but it generates valid emitter functions for the GTK bindings at least.

Remaining issues:
- Proper nullability of return values
- Option usage for arguments correctly
- Bounds

All this should ideally come from the same configuration as for the signals, but the types don't match up with the function analysis/code generator that already does the same.

Do you have any suggestions how to do this best without huge changes? Any other review comments already?

cc @EPashkin

### CODE REVIEW

**Comment by sdroege** [comment]
In theory the function signature from the trampolines should be possible to re-use here.

**Comment by sdroege** [comment]
Ok, I have it using the trampoline's information now. That should make it complete, except for possibly ugly code. Any suggestions? :)

**Comment by sdroege** [comment]
Works in GTK and gstreamer-app, not sure where else there are action signals.

**Comment by GuillaumeGomez** [comment]
I'll update once merged then. :)

**Comment by sdroege** [comment]
Great, I'm out of battery now :) I'm going to do the other regens (also for new bitflags) once this is merged, and the -sys change.

**Comment by sdroege** [comment]
Don't worry, I did and I am :p

**Comment by EPashkin** [comment]
@sdroege Big thanks.

**Comment by sdroege** [comment]
We could implement signal connectors similarly now, around Closure. No unsafe code or trampolines needed anymore

**Comment by EPashkin** [comment]
Not sure that it possible to signals like https://github.com/gtk-rs/gtk/blob/master/src/signal.rs#L268-L281 and others in this file, but it was good if it done to simpler cases.

**Comment by sdroege** [comment]
Uh what is that!? What an awful and Hindi g unfriendly API :) yes that won't be handled because G_TYPE_POINTER. That always needs manual bindings

**Pull request merged**
