### PR TITLE
generate cfg conditions for aliases, enums, interfaces and disguised

### PR DESCRIPTION
**Pull request by fbrouille**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Would you mind submitting a PR to at least gtk-rs-core/gtk4-rs with the changes to see how it looks like?

**Review by sdroege — APPROVED** [review]

**Comment by sdroege** [comment]
Looks good to me but having a pre-view of the changes would be useful indeed.

**Comment by bilelmoussaoui** [comment]
The CI should be fixed once https://github.com/gtk-rs/gtk3-rs/pull/817 is merged

**Comment by sdroege** [comment]
Ok, let's merge it then. Thanks!

**Pull request merged**
