### PR TITLE
Fix generating array with c:type="gpointer*" and other actual type

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gio/pull/131

cc @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
In gtk-rs crates only affect gio-sys.
```diff
--- a/gio-sys/src/lib.rs
+++ b/gio-sys/src/lib.rs
@@ -8237,8 +8237,8 @@ extern "C" {
     pub fn g_list_store_remove_all(store: *mut GListStore);
     #[cfg(any(feature = "v2_46", feature = "dox"))]
     pub fn g_list_store_sort(store: *mut GListStore, compare_func: glib::GCompareDataFunc, user_data: gpointer);
-    //#[cfg(any(feature = "v2_44", feature = "dox"))]
-    //pub fn g_list_store_splice(store: *mut GListStore, position: c_uint, n_removals: c_uint, additions: /*Metadata mismatch*/*mut [c:type mismatch gpointer != GObject of Object], n_additions: c_uint);
+    #[cfg(any(feature = "v2_44", feature = "dox"))]
+    pub fn g_list_store_splice(store: *mut GListStore, position: c_uint, n_removals: c_uint, additions: *mut *mut gobject::GObject, n_additions: c_uint);
```

**Comment by sdroege** [comment]
Nice, that's what I tried except for adding the other `*mut` :) is that always correct?

Thanks!

**Comment by EPashkin** [comment]
IMHO is correct: `glib_type` is type name and it not contains `"*"`, but `c:type` says that it passed as `gpointer` so we add `"*"`.
Anyway its very rare occurrence.

**Comment by sdroege** [comment]
Great! You regen sys?

**Pull request merged**
