### PR TITLE
Revert "Drop version detection in favor of features, add version support for enum variants"

### PR DESCRIPTION
**Pull request by gkoz**
Backing out the mistaken #208. I'll salvage good commits from it.

### CODE REVIEW

**Comment by EPashkin** [comment]
Not better just repush master if it really that bad?

**Comment by EPashkin** [comment]
Or github will be bad with it?

**Comment by gkoz** [comment]
Okay, I suppose it won't affect a lot of people.

**Comment by gkoz** [comment]
Rolled back `master`.

**Comment by EPashkin** [comment]
Will you recreate `version_features` PR with WIP status? Or it unfixable?

**Comment by gkoz** [comment]
Basically removing the build scripts was nonsense, they should at least emit `cargo:rustc-link-lib={package_name}` but perhaps even try calling `pkg-config` (but not fail if it's absent). So that is the part, which needs to be rewritten. The other commits will remain but I might have to resolve some merge conflicts.

**Pull request closed without merging**
