### PR TITLE
Fix invalid gboolean generation

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
When generating glib, I had a "little" issue because of this one.

cc @EPashkin

### CODE REVIEW

**Comment by sdroege** [comment]
:+1:

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks.
I merge this but IMHO all `idle_*` and `timeout_` in glib need be manual as return `SourceId`

**Comment by GuillaumeGomez** [comment]
We still have issues with `g_child_watch_add*` because of aliases. I'm ending the patch then here we go!

**Comment by sdroege** [comment]
All those source/watch related things have to be manually written (and are already).

**Comment by sdroege** [comment]
> All those source/watch related things have to be manually written (and are already).

Among other things, they only require `Send` for the closure, can be `FnMut()` (and are already), return a `SourceId` and the closure returns a `Continue`.

**Pull request merged**
