### PR TITLE
Add underscore to Enum/Flag names starting with digit

### PR DESCRIPTION
**Pull request by antunonline**
This had to be done in order to enable of genration of NetworkManager library bindings (not all bindings)

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
That is an issue on the C api, it should be fixed instead.

**Comment by antunonline** [comment]
This is a part of NetworkManager API which has been in a such state for a long time. 
I'm not sure that I can influence them to change it, nor I have the time to analyze how NM works and prepare pull requests for it. 

I would rather add ability to circumvent this issues on gir side and create pull requests here. 

I know that the pull requests are not perfect, but if we can find some compromise without me spending a lot of time, enabling other uses to also create NetworkManager bindings, I would rather to that.

**Comment by bilelmoussaoui** [comment]
Sure, as long as it is documented as such

> I know that the pull requests are not perfect, but if we can find some compromise without me spending a lot of time, enabling other uses to also create NetworkManager bindings, I would rather to that.

You can also change the gir file to fix it without changing the API upstream

**Comment by antunonline** [comment]
This is quite a complicated procedure and I'm not sure that it's the proper way to do it, because then every user should
understand how it all works, and repeat the procedure from the start. 

It's not a copy and run experience. 

I think that I'll have to take some time to dive deeper into the project and prepare proper patches to support it 
without adding technical debt.

**Comment by antunonline** [comment]
I'll close it for now, until I prepare better code

**Pull request closed without merging**
