### PR TITLE
Apply configured return.nullable to out parameters

### LINKED ISSUE #306: Allow override nullable return value when the return type is Result<T, Error>
Hello.
It seems that it is not possible to use `nullable = true` for a return value when its type is `Result<T, Error>`.
For instance, I would like [this method](https://github.com/antoyo/webkit2gtk-webextension-rs/blob/master/src/auto/dom_element.rs#L116) to be able to return `None`.
So, using `nullable = true` should generate the type `Result<Option<DOMElement>, Error>`, but `gir` currently generates the type `Result<DOMElement, Error>`.
Could you please fix this issue?
Thanks.

### PR DESCRIPTION
**Pull request by EPashkin**
Closes #306

@antoyo, check this version please.

### CODE REVIEW

**Comment by antoyo** [comment]
I have errors when trying to compile this:

```
error: no method named `at` found for type `&regex::Captures<'_>` in the current scope
  --> src/codegen/doc/format.rs:92:62
   |
92 |         format!("{}`{}{}`", &caps[1], lookup(&caps[2]), caps.at(3).unwrap_or(""))
   |                                                              ^^

error[E0308]: mismatched types
   --> src/codegen/doc/format.rs:101:5
    |
101 |     SPACES.replace_all(&out, " ")
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::string::String`, found enum `std::borrow::Cow`
    |
    = note: expected type `std::string::String`
    = note:    found type `std::borrow::Cow<'_, str>`
    = help: here are some functions which might fulfill your needs:
            - .escape_debug()
            - .escape_default()
            - .escape_unicode()
            - .to_lowercase()
            - .to_uppercase()

error[E0308]: mismatched types
   --> src/codegen/doc/mod.rs:268:5
    |
268 |       PARAM_NAME.replace_all(doc, |caps: &Captures| {
    |  _____^ starting here...
269 | |         if let Some(ref self_name) = *self_name {
270 | |             if &caps[1] == self_name {
271 | |                 return "@self".into()
272 | |             }
273 | |         }
274 | |         format!("@{}", nameutil::mangle_keywords(&caps[1]))
275 | |     })
    | |______^ ...ending here: expected struct `std::string::String`, found enum `std::borrow::Cow`
    |
    = note: expected type `std::string::String`
    = note:    found type `std::borrow::Cow<'_, str>`
    = help: here are some functions which might fulfill your needs:
            - .escape_debug()
            - .escape_default()
            - .escape_unicode()
            - .to_lowercase()
            - .to_uppercase()

error[E0277]: the trait bound `std::vec::Vec<std::string::String>: std::iter::FromIterator<std::borrow::Cow<'_, str>>` is not satisfied
  --> src/codegen/sys/build.rs:41:10
   |
41 |         .collect();
   |          ^^^^^^^ the trait `std::iter::FromIterator<std::borrow::Cow<'_, str>>` is not implemented for `std::vec::Vec<std::string::String>`
   |
   = note: a collection of type `std::vec::Vec<std::string::String>` cannot be built from an iterator over elements of type `std::borrow::Cow<'_, str>`

error[E0277]: the trait bound `regex::Regex: std::cmp::Eq` is not satisfied
 --> src/config/ident.rs:7:13
  |
7 |     Pattern(Regex),
  |             ^^^^^^ the trait `std::cmp::Eq` is not implemented for `regex::Regex`
  |
  = note: required by `std::cmp::AssertParamIsEq`

error[E0369]: binary operation `==` cannot be applied to type `regex::Regex`
 --> src/config/ident.rs:7:13
  |
7 |     Pattern(Regex),
  |             ^^^^^^
  |
note: an implementation of `std::cmp::PartialEq` might be missing for `regex::Regex`
 --> src/config/ident.rs:7:13
  |
7 |     Pattern(Regex),
  |             ^^^^^^

error[E0369]: binary operation `!=` cannot be applied to type `regex::Regex`
 --> src/config/ident.rs:7:13
  |
7 |     Pattern(Regex),
  |             ^^^^^^
  |
note: an implementation of `std::cmp::PartialEq` might be missing for `regex::Regex`
 --> src/config/ident.rs:7:13
  |
7 |     Pattern(Regex),
  |             ^^^^^^

error: aborting due to 7 previous errors

error: Could not compile `gir`.

To learn more, run the command again with --verbose.
```

I tried `cargo update`.

**Comment by EPashkin** [comment]
Your right. `Cargo update` was bad idea :wink: But it build with original `Cargo.lock` ?

**Comment by antoyo** [comment]
I used `cargo update` because with the original file, I have the following error:

```
error[E0432]: unresolved import `git_status_show_t::*`
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.3.9/lib.rs:536:9
    |
536 | pub use git_status_show_t::*;
    |         ^^^^^^^^^^^^^^^^^^^^^ Not a module `git_status_show_t`

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: Could not compile `libgit2-sys`.
```

**Comment by EPashkin** [comment]
For me after update in lock file line `"libgit2-sys 0.4.6 (registry+https://github.com/rust-lang/crates.io-index)",` don't changed.

**Comment by EPashkin** [comment]
And my (and stored in repo) git2version is `"git2 0.4.4 (registry+https://github.com/rust-lang/crates.io-index)",`

**Comment by antoyo** [comment]
I've had issues with my branches.
I tested this and it works fine.
Thanks.

**Pull request merged**
