### PR TITLE
sys: run ABI tests only under linux

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
they need more work to work on other platforms for now

### CODE REVIEW

**Comment by sdroege** [comment]
Can't this be put directly into the `Cargo.toml`?

**Comment by bilelmoussaoui** [comment]
No idea, it would also mean writing more code to override more stuff in the -sys Cargo.toml

**Comment by sdroege** [comment]
Ok then :)

**Comment by bilelmoussaoui** [comment]
It seems like there is a `autotests = false` config but it can't be set per target_os

**Review by sdroege — APPROVED** [review]

**Review by sdroege — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
Let us try those new super powers!

**Pull request merged**
