### PR TITLE
analysis: mark to_str functions as renamed

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Instead of overriding their original names; this makes the docs work without workarounds
by marking them as renamed manually like in https://github.com/gtk-rs/gtk4-rs/pull/656

### CODE REVIEW

**Comment by sdroege** [comment]
@bilelmoussaoui This broke gstreamer-rs :)

```
thread 'main' panicked at 'A `to_string` function can't be renamed manually. It's automatically renamed to `to_str`', src/analysis/special_functions.rs:106:13
```

**Comment by bilelmoussaoui** [comment]
@sdroege not really, you just need to drop https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/blob/master/gstreamer-video/Gir.toml#L545

**Comment by bilelmoussaoui** [comment]
as it's already marked as renamed automatically for you

**Comment by MarijnS95** [comment]
We'll have to keep the manual setup though, but the `rename =` can be dropped and maybe the return too?

**Comment by bilelmoussaoui** [comment]
> We'll have to keep the manual setup though, but the `rename =` can be dropped and maybe the return too?

Yes, sorry I wanted to link to the rename only

**Comment by sdroege** [comment]
Oh I see, thanks

**Pull request merged**
