### PR TITLE
Fixed processing of properties "construct_only" flag

### PR DESCRIPTION
**Pull request by EPashkin**
Affected modules gio, gdk, gtk

### CODE REVIEW

**Comment by EPashkin** [comment]
By misprint gir generating many not working setters for properties like https://developer.gnome.org/gtk3/stable/GtkAssistant.html#GtkAssistant--use-header-bar

**Comment by EPashkin** [comment]
@GuillaumeGomez I right about "construct-only" really not writable?

**Comment by GuillaumeGomez** [comment]
I think yes. It's not intended to be modified after being initialized. Thanks!

**Comment by EPashkin** [comment]
I will update gio, gdk, gtk after @aruiz fixed #328 and it merged.
May be in this time I also fix #332

**Comment by GuillaumeGomez** [comment]
Ok! I'll try to go back on my PR as well in the next week.

**Pull request merged**
