### PR TITLE
Remove into bound for user callbacks

### LINKED ISSUE #713: Into<Option<_>> considered harmful
For closures this requires type annotations everywhere to make the compiler happy and we should really remove it there to make those functions easy to use for the user. Adding a `Some()` around the closure is easy, annotating everything correctly not so much.

IMHO we should get rid of this in general also for other parameter types but that probably needs some wider discussion first. Apart from annotation mess (but less likely) it also makes it much harder for users to discover that they can also pass `None` (common question by people) and the type signature is harder to read.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #713.

cc @EPashkin @sdroege

### CODE REVIEW

**Comment by sdroege** [comment]
Yeah that's too much. It should instead be `P: Option<Fn(i32) ...>`

**Comment by GuillaumeGomez** [comment]
Okay, `Option` is now back!

**Comment by GuillaumeGomez** [comment]
cc @EPashkin @sdroege

**Comment by EPashkin** [comment]
Thanks, but this case also have problem: old case has was good with just type, your need Some and type

**Comment by GuillaumeGomez** [comment]
Do you have an example so I can improve my code? :)

**Comment by EPashkin** [comment]
I don't have, tried playground for simplified cases all not good 😢

**Comment by GuillaumeGomez** [comment]
So what do you want me to change in here?

**Comment by sdroege** [comment]
Don't generate any `Option<_>` in any way for callbacks, and print a warning for each such function that manual implementations might be necessary because of that.

**Comment by GuillaumeGomez** [comment]
I'm almost done here. Need to find out why some `Into` bounds are removed and then we're good.

**Comment by GuillaumeGomez** [comment]
Ok, here we go!

**Comment by sdroege** [comment]
>  fn set_forward_page_func(&self, page_func: Option<&( dyn Fn(i32) -> i32 + 'static)>) {

Why the parenthesis and the space before the `dyn`? That should both not be needed :)

Also this one should take a `Box<dyn Fn ...>`, it's not `scope call`. This is going to crash in interesting ways :)

`scope notified` should use boxed trait objects, `scope call` should use `Option<&mut dyn FnMut...>`

----

Once that is fixed, can you paste one example for `scope notified` and another for `scope call`?

**Comment by sdroege** [comment]
Just to be clear, the parameter for `scope notified` must be `Option<Box<dyn Fn...>>`. You only box that box a second time inside the function for making it 1 pointers big instead of 2.

For `scope call` you don't have any box anywhere, but the parameter is `func: Option<&mut dyn Fn...>` and you then have to pass `&mut func as *mut _` to the C function and in the trampoline you'll get out a `*mut *mut dyn Fn` (note the double indirection: this is the same as the double boxing in the other case but without heap allocation!).

**Comment by GuillaumeGomez** [comment]
Sure!

**Comment by GuillaumeGomez** [comment]
notified:

<details>

```rust
fn set_forward_page_func(&self, page_func: Option<Box<dyn Fn(i32) -> i32 + 'static>>) {
    let page_func = page_func.into();
    let page_func_data: Box_<Option<Box<dyn Fn(i32) -> i32 + 'static>>> = Box::new(page_func);
    unsafe extern "C" fn page_func_func(current_page: libc::c_int, data: glib_ffi::gpointer) -> \
libc::c_int {
        let callback: &Option<Box<dyn Fn(i32) -> i32 + 'static>> = &*(data as *mut _);
        let res = if let Some(ref callback) = *callback {
            callback(current_page)
        } else {
            panic!("cannot get closure...")
        };
        res
    }
    let page_func = if page_func_data.is_some() { Some(page_func_func::<> as _) } else { None };
    unsafe extern "C" fn destroy_func(data: glib_ffi::gpointer) {
        let _callback: Box_<Option<Box<dyn Fn(i32) -> i32 + 'static>>> = Box_::from_raw(data as \
*mut _);
    }
    let destroy_call3 = Some(destroy_func::<> as _);
    let super_callback0: Box_<Option<Box<dyn Fn(i32) -> i32 + 'static>>> = page_func_data;
    unsafe {
        ffi::gtk_assistant_set_forward_page_func(self.as_ref().to_glib_none().0, page_func, Box:\
:into_raw(super_callback0) as *mut _, destroy_call3);
    }
}
```
</details>

call:

<details>

```rust
fn invalidate_maybe_recurse(&self, region: &cairo::Region, child_func: Option<&mut dyn (FnMut(&W\
indow) -> bool)>) {
    let child_func_data: Option<&mut dyn (FnMut(&Window) -> bool)> = child_func;
    unsafe extern "C" fn child_func_func(window: *mut ffi::GdkWindow, user_data: glib_ffi::gpoin\
ter) -> glib_ffi::gboolean {
        let window = from_glib_borrow(window);
        let callback: *mut Option<&mut dyn (FnMut(&Window) -> bool)> = user_data as *const _ as \
usize as *mut Option<&mut dyn (FnMut(&Window) -> bool)>;
        let res = if let Some(ref mut callback) = *callback {
            callback(&window)
        } else {
            panic!("cannot get closure...")
        };
        res.to_glib()
    }
    let child_func = Some(child_func_func::<> as _);
    let super_callback0: &Option<&mut dyn (FnMut(&Window) -> bool)> = &child_func_data;
    unsafe {
        ffi::gdk_window_invalidate_maybe_recurse(self.as_ref().to_glib_none().0, region.to_glib_\
none().0, child_func, super_callback0 as *const _ as usize as *mut _);
    }
}
```

**Comment by sdroege** [comment]
> page_func_func::<>

I didn't know this even compiles :) But fine with keeping it if it doesn't break the compiler.

Looks good to me otherwise.

**Comment by GuillaumeGomez** [comment]
Me neither! I'll clean that up!

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by sdroege** [comment]
All good for me then

**Comment by EPashkin** [comment]
So part ` && *trampoline.nullable` makes no difference?
This is strange, and if it true, then IMHO better removed, even it it was needed before

**Comment by GuillaumeGomez** [comment]
Fine by me!

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by EPashkin** [comment]
@GuillaumeGomez  Thanks, lets merge this.

**Comment by GuillaumeGomez** [comment]
:tada: I'll send the PRs this evening (except for gtk which is handled through @sdroege's PR).

**Pull request merged**
