### PR TITLE
Drop version detection in favor of features, add version support for enum variants

### PR DESCRIPTION
**Pull request by gkoz**
This should ensure better API stability control as described in https://github.com/gtk-rs/gtk/issues/243 (new upstream library versions support should not introduce breaking changes in code that sticks to earlier versions).

### CODE REVIEW

**Comment by EPashkin** [comment]
No problem with code.
2 possible problems with sys generation:
1. Features in 'atk-sys\Cargo.toml` sorted as strings.
2. sys_build build only basic version (3.4)?

**Comment by gkoz** [comment]
> Features in 'atk-sys\Cargo.toml` sorted as strings.

The toml library is the limit factor here. Hopefully a ["round-trippable" fork](https://github.com/vosen/toml_document) will be ready soon.

> sys_build build only basic version (3.4)?

Yeah, I should upgrade the test script.

**Comment by EPashkin** [comment]
Configuring "Gdk.EventType" better moved to `tests\sys\gir-gdk.toml`

**Comment by EPashkin** [comment]
Don't see `touchpad_swipe` and `touchpad_pinch` in `Gdk.EventType` in sys. Seems `gir-files` need update.

**Comment by gkoz** [comment]
That's right. I keep putting off the update to 3.18 because it could break some assumptions in the generator but we should probably try it anyway. And also because the last time I built GTK+ 3.18 it seemed to require an unreleased cairo version.

**Comment by EPashkin** [comment]
Wrong file for `EventType config`? `tests/sys/gir-gdk-pixbuf.toml`

**Comment by EPashkin** [comment]
Thanks.

**Comment by EPashkin** [comment]
We forgot commit `tests/sys/*/Cargo.toml` after rebuild

**Comment by gkoz** [comment]
Hmm yes, although the generator does the right thing to them now, stale manifests could cause problems in the future.

**Comment by gkoz** [comment]
Apparently I haven't researched and tested the linking changes properly so this might have to be reverted, I'll be more sure tomorrow.

**Pull request merged**
