### PR TITLE
Add StyleContext to Gir_Gtk.toml. It has many issues

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by EPashkin** [comment]
Other candidates:
for #130 file_chooser (file_chooser_widged already added) or builder,
for #144 cell_area or tree_selection

**Comment by EPashkin** [comment]
Also with StyleConcext better add StyleProvider(interface) and Border(record with methods)

**Comment by EPashkin** [comment]
Forget about my add proposal for Border as records currently not realized #103

**Comment by EPashkin** [comment]
`StyleContext` already added in `gtk`.
This PR can be merged after fix or closed.

**Comment by gkoz** [comment]
It still has some problems though, mostly because of records handling.

`gdk::RGBA` is a 'plain old data' record. I'm reluctant to implement `From/ToGlibPtr` wrapper fot it but then the generator needs to distinguish POD records from wrapped ones.

`WidgetPath` doesn't seem to be supported currently.

**Comment by EPashkin** [comment]
About `gdk::RGBA`: we can add `RecordType::POD` with assigned in same case as `RecordType::Direct` if some parameter set in config.
For that type we can: a) don't generate `.rs` and define it manually, b) use conversion specific for POD records

**Comment by gkoz** [comment]
Okay, distinguishing between how `GdkRGBA` and `GdkRectangle` are handled seems too much trouble. Let's just have a single `RecordType` for this case and either assume the From/To conversions exist or generate them if possible. This way we can avoid reexporting any of them from the sys crates.

I'm not sure I understand the `Direct` variant. It seems to imply passing by value. There is a sort of by-value case with arrays of `GtkPageRange`.

**Comment by EPashkin** [comment]
@gkoz Can we close this? `StyleContext` was added to gtk long ago

**Comment by gkoz** [comment]
Okay.

**Pull request closed without merging**
