### PR TITLE
Fix display

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks. Just waiting CI.
Feel free to merge if you want speedup process or just see that CI passed.

**Comment by sdroege** [comment]
:+1:

**Comment by EPashkin** [comment]
Strange, now I get error in glib: only `impl fmt::Display for Binding` generated without `use std::fmt;`
```
  --> D:/eap/rust/0/glib\src\gobject\auto\binding.rs:64:6
   |
64 | impl fmt::Display for Binding {
   |      ^^^ Use of undeclared type or module `fmt`

error[E0433]: failed to resolve. Use of undeclared type or module `fmt`
```

**Comment by GuillaumeGomez** [comment]
@EPashkin thanks, taking a look!

**Comment by EPashkin** [comment]
@GuillaumeGomez Ignore it, just missed local change :sob:

**Comment by GuillaumeGomez** [comment]
I was wondering what I was missing haha.

**Pull request merged**
