### PR TITLE
Tests cairo

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by EPashkin** [comment]
Seems you was right about not full cairo-1.0.gir.
Just in case I check for build other syses with this.

**Comment by gkoz** [comment]
It's possible to generate a complete definition but we probably won't need that for a while.

**Comment by EPashkin** [comment]
It allow `gtk` compile, but not contain functions, used in original `cairo`.
Not sure merge this or stay open or close.

**Comment by EPashkin** [comment]
If you want merge, wait for rebase after previous PR.

**Comment by EPashkin** [comment]
Rebased

**Comment by gkoz** [comment]
I'll let this sit until we have a better idea of what to do with cairo. Merging now could hide some conflicts with the existing crate.

**Comment by EPashkin** [comment]
It too old and seems unneeded

**Pull request closed without merging**
