### PR TITLE
Cows

### PR DESCRIPTION
**Pull request by EPashkin**
WIP.

Now `gtk` generated `2min on my old PC, so I start trying to faster it by remove unneeded copying.
Seems I started with wrong part as changes give no effect at all :(

### CODE REVIEW

**Comment by gkoz** [comment]
Yeah guessing what causes slowness isn't productive. You'd need to use a profiler. Not sure if there are tools that can profile binaries built for the `-gnu` target or if it's possible to use the `-msvc` target. 

There's a chance that most of the time is spent the XML parser. It could be an interesting experiment to serialize `Library` into a faster to parse format and cache that representation.

**Comment by EPashkin** [comment]
Yes, only effect of this PR is increasing build time, so I postpone it and start adding statistics gatherer.

**Comment by gkoz** [comment]
Running under callgrind shows this instruction number distribution suggesting that parsing does indeed dwarf everything else.
```
57,308,350  => config::Config::new
12,133,476,457  => library::Library::read_file
1,165,692  => library::Library::postprocessing
5,866,579  => analysis::class_hierarchy::run
486,227,927  => codegen::generate
51,075,239  => env::Env::drop
```
(everything else is under 1 million).

**Comment by EPashkin** [comment]
So it just reading Library?

**Comment by EPashkin** [comment]
By https://github.com/gtk-rs/gir/pull/248 it doing something other: loading only 5sec from 26 or 121

**Comment by EPashkin** [comment]
This needed no more, closing

**Pull request closed without merging**
