### PR TITLE
Fix panic on generating gdk-pixbuf-sys

### PR DESCRIPTION
**Pull request by EPashkin**
Fix [panic when generating gdk-pixbuf-sys](https://github.com/gtk-rs/gir/pull/548#issuecomment-366976512)
Also see #549

@tmiasko please, can you confirm that it works without adding "generate" to sys?

### CODE REVIEW

**Comment by tmiasko** [comment]
Yes, this works as well. BTW, you don't have the same problem, or just don't generate gdk-pixbuf-sys?

**Comment by EPashkin** [comment]
@tmiasko I usually generate all syses in one go and just missed that one panics.
Thanks for reporting.

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege Strange that `analysis::run` was called in sys mode,
its result not used in sys generation.
So I disabled call.

**Comment by GuillaumeGomez** [comment]
Fine by me.

**Pull request merged**
