### PR TITLE
Use error_chain crate to process errors

### PR DESCRIPTION
**Pull request by EPashkin**
Use [error-chain](https://crates.io/crates/error-chain) crate to handle errors
Before
```
Failed to read config "D:\eap\rust\0\gtk\Gir.toml1": File not found. (os error 2)
```
now
```
Failed to read config "D:\eap\rust\0\gtk\Gir.toml1"
caused by: File not found. (os error 2)
```
Config file name moved to special parent error and children not needed it anymore and just changed to strings.
Before
```
"D:\eap\rust\0\gtk\Gir.toml": No options.girs_dir in config
```
now
```
Error in config "D:\eap\rust\0\gtk\Gir.toml"
caused by: No options.girs_dir
```

cc @GuillaumeGomez, @gkoz 

PS. `error-chain` can collect backtrace of errors, but currently I disabled this.
Enabling feature "backtrace" add 5 more crates

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I just saw the crate very recently and it looked really promising, so big 👍 for me!

Don't hesitate to ping once you're done editing the PR.

**Comment by EPashkin** [comment]
Appveyor fails on 1.13 for unknown reason https://ci.appveyor.com/project/GuillaumeGomez/gir/build/1.0.224/job/7vot4xpaknxwfexm
And in 1.12 fails `error_chain` due unstable feature

**Comment by EPashkin** [comment]
I have no idea where it fails, logs says that it reach last line in `main` https://ci.appveyor.com/project/GuillaumeGomez/gir/build/1.0.229/job/7h5546m5y928x06g

**Comment by EPashkin** [comment]
Removing lib-secret don't help too https://ci.appveyor.com/project/GuillaumeGomez/gir/build/1.0.230/job/vq5l35wnnxh8pe7o

**Comment by GuillaumeGomez** [comment]
Seems all good now. Ready to merge?

**Comment by EPashkin** [comment]
Almost ready, I want rename grid;s child properties to cell,
I add PR to examples that fail, and after merged do renaming

**Comment by EPashkin** [comment]
Ignore previous it was about other PR. This is ready to merge

**Comment by GuillaumeGomez** [comment]
This is a change even I can review so I'll merge. Thanks!

**Pull request merged**
