### PR TITLE
Add dox feature in order to build all docs, whatever the platform

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Since [rustc/43348](https://github.com/rust-lang/rust/pull/43348) has been merged, we can now do this!

cc @EPashkin @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
`sys/cargo_toml.rs` don't need changed too with adding feature? Or `dox` internal config and always present?

**Comment by GuillaumeGomez** [comment]
Hum, good question. I thought it was a "provided" feature. Let me check.

Also, we'll need to add into the libs the following line:

```rust
#![cfg_attr(dox, feature(doc_cfg)]
```

So that people don't get struggle while trying to build it in stable.

**Comment by QuietMisdreavus** [comment]
Scratch that on the `cfg_attr`. You're not using the thing that's behind that feature gate (the thing introduced in that PR linked at the top), so it's not necessary to add.

**Comment by GuillaumeGomez** [comment]
@gkoz: So you were right, we'll need to add a new feature:

```toml
dox = []
```

It's completely unrelated to the other PR, we can just play with this. No need for `cfg_attr` either. I updated the PR.

**Comment by EPashkin** [comment]
So it ready for merge?

**Comment by GuillaumeGomez** [comment]
Yep, I'll need to update the crates though.

**Comment by EPashkin** [comment]
@GuillaumeGomez thanks

**Comment by EPashkin** [comment]
@GuillaumeGomez sys have problem with this: hook_size_and_setup, GMutex not have 2 definition when I try run `cargo doc --features="dox"`.
Not sure how to fix it :(

**Comment by EPashkin** [comment]
*now have 2 definition

**Comment by GuillaumeGomez** [comment]
Ah. I suppose it's coming from the double target... I didn't think about such a case. Maybe I should add a check to see if a type is defined in two different cfgs?

**Comment by EPashkin** [comment]
I was too lazy and don't check from where this code go.
As it come from string I just add PR to fix it

**Comment by GuillaumeGomez** [comment]
Fine by me.

**Pull request merged**
