### PR TITLE
Add default values for fundamental types and Records

### PR DESCRIPTION
**Pull request by EPashkin**
Replacement of #328

### CODE REVIEW

**Comment by EPashkin** [comment]
Needed ignore one getter in Gtk
```
[[object]]
name = "Gtk.Actionable"
status = "generate"
    [[object.property]]
    #value glib.Variant
    name = "action-target"
    ignore = true
```

**Comment by EPashkin** [comment]
IMHO this property has getter https://developer.gnome.org/gtk3/stable/GtkActionable.html#gtk-actionable-get-action-target-value, then comment #value can removed as property ignored by different reason

**Comment by GuillaumeGomez** [comment]
Not working:

```
error[E0277]: the trait bound `glib::Variant: glib::IsA<glib::Object>` is not satisfied
  --> src/auto/actionable.rs:75:25
   |
75 |         let mut value = Value::from(None::<&glib::Variant>);
   |                         ^^^^^^^^^^^ the trait `glib::IsA<glib::Object>` is not implemented for `glib::Variant`
   |
   = note: required because of the requirements on the impl of `glib::value::SetValueOptional` for `glib::Variant`
   = note: required because of the requirements on the impl of `std::convert::From<std::option::Option<&glib::Variant>>` for `glib::Value`
   = note: required by `std::convert::From::from`

error[E0277]: the trait bound `glib::Variant: glib::IsA<glib::Object>` is not satisfied
  --> src/auto/actionable.rs:79:15
   |
79 |         value.get()
   |               ^^^ the trait `glib::IsA<glib::Object>` is not implemented for `glib::Variant`
   |
   = note: required because of the requirements on the impl of `glib::value::FromValueOptional` for `glib::Variant`

error: aborting due to 2 previous errors
```

**Comment by EPashkin** [comment]
https://github.com/gtk-rs/gir/pull/358#issuecomment-298190578

I also forgot about https://github.com/gtk-rs/gir/issues/356, IMHO better wait until I do it
But if you want add WIP PR won't forget https://github.com/gtk-rs/gir/issues/356#issuecomment-298172684 please

**Comment by GuillaumeGomez** [comment]
It's a small change so we can wait for it. Let's just try to avoid keeping this broken state for too long.

**Comment by EPashkin** [comment]
Last delay only related to Gtk, all other crates can be updated

**Comment by GuillaumeGomez** [comment]
Ok, doing it then!

**Comment by EPashkin** [comment]
I off for today.
All crates builds for me after regen, so please merge without my review.

**Comment by GuillaumeGomez** [comment]
Ok!

**Comment by GuillaumeGomez** [comment]
Glib is broken as well:

```
error: field `g_type` of struct `gobject_ffi::GValue` is private
   --> src/value.rs:143:19
    |
143 |         from_glib(self.0.g_type)
    |                   ^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/lib.rs:134:79
    |
134 |   pub static ref KEY_FILE_DESKTOP_GROUP: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_GROUP).to_str().unwrap()};
    |                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:135:85
    |
135 |   pub static ref KEY_FILE_DESKTOP_KEY_ACTIONS: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_ACTIONS).to_str().unwrap()};
    |                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:136:88
    |
136 |   pub static ref KEY_FILE_DESKTOP_KEY_CATEGORIES: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_CATEGORIES).to_str().unwrap()};
    |                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:137:85
    |
137 |   pub static ref KEY_FILE_DESKTOP_KEY_COMMENT: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_COMMENT).to_str().unwrap()};
    |                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:138:94
    |
138 |   pub static ref KEY_FILE_DESKTOP_KEY_DBUS_ACTIVATABLE: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_DBUS_ACTIVATABLE).to_str().unwrap()};
    |                                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:139:82
    |
139 |   pub static ref KEY_FILE_DESKTOP_KEY_EXEC: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_EXEC).to_str().unwrap()};
    |                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:140:86
    |
140 |   pub static ref KEY_FILE_DESKTOP_KEY_FULLNAME: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_FULLNAME).to_str().unwrap()};
    |                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:141:90
    |
141 |   pub static ref KEY_FILE_DESKTOP_KEY_GENERIC_NAME: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_GENERIC_NAME).to_str().unwrap()};
    |                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:142:92
    |
142 |   pub static ref KEY_FILE_DESKTOP_KEY_GETTEXT_DOMAIN: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_GETTEXT_DOMAIN).to_str().unwrap()};
    |                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:143:84
    |
143 |   pub static ref KEY_FILE_DESKTOP_KEY_HIDDEN: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_HIDDEN).to_str().unwrap()};
    |                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:144:82
    |
144 |   pub static ref KEY_FILE_DESKTOP_KEY_ICON: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_ICON).to_str().unwrap()};
    |                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:145:86
    |
145 |   pub static ref KEY_FILE_DESKTOP_KEY_KEYWORDS: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_KEYWORDS).to_str().unwrap()};
    |                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:146:87
    |
146 |   pub static ref KEY_FILE_DESKTOP_KEY_MIME_TYPE: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_MIME_TYPE).to_str().unwrap()};
    |                                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:147:82
    |
147 |   pub static ref KEY_FILE_DESKTOP_KEY_NAME: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_NAME).to_str().unwrap()};
    |                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:148:89
    |
148 |   pub static ref KEY_FILE_DESKTOP_KEY_NOT_SHOW_IN: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_NOT_SHOW_IN).to_str().unwrap()};
    |                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:149:88
    |
149 |   pub static ref KEY_FILE_DESKTOP_KEY_NO_DISPLAY: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_NO_DISPLAY).to_str().unwrap()};
    |                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:150:90
    |
150 |   pub static ref KEY_FILE_DESKTOP_KEY_ONLY_SHOW_IN: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_ONLY_SHOW_IN).to_str().unwrap()};
    |                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:151:82
    |
151 |   pub static ref KEY_FILE_DESKTOP_KEY_PATH: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_PATH).to_str().unwrap()};
    |                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:152:92
    |
152 |   pub static ref KEY_FILE_DESKTOP_KEY_STARTUP_NOTIFY: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_STARTUP_NOTIFY).to_str().unwrap()};
    |                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:153:94
    |
153 |   pub static ref KEY_FILE_DESKTOP_KEY_STARTUP_WM_CLASS: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_STARTUP_WM_CLASS).to_str().unwrap()};
    |                                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:154:86
    |
154 |   pub static ref KEY_FILE_DESKTOP_KEY_TERMINAL: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_TERMINAL).to_str().unwrap()};
    |                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:155:86
    |
155 |   pub static ref KEY_FILE_DESKTOP_KEY_TRY_EXEC: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_TRY_EXEC).to_str().unwrap()};
    |                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:156:82
    |
156 |   pub static ref KEY_FILE_DESKTOP_KEY_TYPE: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_TYPE).to_str().unwrap()};
    |                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:157:81
    |
157 |   pub static ref KEY_FILE_DESKTOP_KEY_URL: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_URL).to_str().unwrap()};
    |                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:158:85
    |
158 |   pub static ref KEY_FILE_DESKTOP_KEY_VERSION: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_KEY_VERSION).to_str().unwrap()};
    |                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:159:90
    |
159 |   pub static ref KEY_FILE_DESKTOP_TYPE_APPLICATION: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_TYPE_APPLICATION).to_str().unwrap()};
    |                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:160:88
    |
160 |   pub static ref KEY_FILE_DESKTOP_TYPE_DIRECTORY: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_TYPE_DIRECTORY).to_str().unwrap()};
    |                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error[E0308]: mismatched types
   --> src/lib.rs:161:83
    |
161 |   pub static ref KEY_FILE_DESKTOP_TYPE_LINK: &'static str = unsafe{CStr::from_ptr(ffi::G_KEY_FILE_DESKTOP_TYPE_LINK).to_str().unwrap()};
    |                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found str
    |
    = note: expected type `*const i8`
               found type `&'static str`

error: aborting due to 29 previous errors

error: Could not compile `glib`.
```

**Comment by EPashkin** [comment]
Seems you forgot get last sys locally
I added PR https://github.com/gtk-rs/glib/pull/161

Also better merge https://github.com/gtk-rs/glib/pull/160 before publish new crate,
but it currently on confirming by `Susurrus`

**Pull request merged**
