### PR TITLE
Add overriding for function trait for manual implemented functions

### PR DESCRIPTION
**Pull request by EPashkin**
Fix https://github.com/gtk-rs/gir/issues/797

@GuillaumeGomez, not sure that it right way, but it works

test for gio:
```diff
+++ b/Gir.toml
@@ -664,11 +664,13 @@ manual_traits = ["SocketListenerExtManual"]
     name = "accept_socket_async"
     # finish function misses nullable return annotation
     ignore = true
+    doc_trait_name = "SocketListenerExtManual"
 
     [[object.function]]
     name = "accept_async"
     # finish function misses nullable return annotation
     ignore = true
+    doc_trait_name = "SocketListenerExtManual"
 
 [[object]]
 name = "Gio.Subprocess"
```

### CODE REVIEW

**Comment by EPashkin** [comment]
Signal need this too 😢

**Comment by EPashkin** [comment]
Properties too, it also generated wrong function_name:
```
<!-- trait CellRendererPixbufExt::fn set_property_icon-name -->
The name of the themed icon to display.
This property only has an effect if not overridden by "stock_id"
or "pixbuf" properties.
```

**Comment by EPashkin** [comment]
I hope that this final version,
@GuillaumeGomez  I will process other crates tomorrow, if you don't want do it yourself

**Comment by EPashkin** [comment]
Checked all gtk-rs crates: PR covered all cases.
@GuillaumeGomez, @sdroege plase, check code.
Also maybe you have better solution than `doc_trait_name`?

**Comment by GuillaumeGomez** [comment]
Isn't it possible to get if the function is in a manual trait directly instead of adding this new key?

**Comment by EPashkin** [comment]
Theoretically we can scan all manual files and store all traits and its functions, then auto-detect its docs,
but at the moment I don't want do parse yourself and use syn too.

**Comment by GuillaumeGomez** [comment]
No need to have a super efficient thing. A little python script which will run through `src` folder and store all "trait *ExtManual" things should be enough no?

**Comment by EPashkin** [comment]
We have many traits like EditableSignals in gtk, so trait name can be any,
and it require parsing anyway.
Also I don't understand how "little python script" helps with "Isn't it possible to get if the function is in a manual trait directly instead of adding this new key?"

**Comment by GuillaumeGomez** [comment]
> Also I don't understand how "little python script" helps with "Isn't it possible to get if the function is in a manual trait directly instead of adding this new key?"

Nothing, sorry. I thought you were talking about finding missing declared manual traits in the gir files... What I meant initially was: "why not using `manual_trait = "SomeExtManual"` when generating docs?

**Comment by EPashkin** [comment]
> I meant initially was: "why not using manual_trait = "SomeExtManual" when generating docs instead of adding a new key?

Mostly because it array `manual_traits = ["DialogExtManual"]`,
also I don't think that all ignored need moved to it.

**Comment by GuillaumeGomez** [comment]
It seems weird to me that it's not possible to just base ourselves on this... What do you think of this @sdroege ?

**Comment by EPashkin** [comment]
Ok, I still think that we can't change trait for all ignored functions,
so I merge this as is.

**Pull request merged**
