### PR TITLE
RFC: Not so twisted snakes.

### PR DESCRIPTION
**Pull request by ghost**
Improve to_snake implementation. For example:

type name    | old module name | new module name
-------------|-----------------|----------------
DBusMessage  | d_bus_message   | dbus_message
FileIOStream | file_i_o_stream | file_iostream
IMContext    | i_m_context     | imcontext
IOStream     | i_o_stream      | iostream
URIHandler   | u_r_i_handler   | urihandler
UnixFDList   | unix_f_d_list   | unix_fdlist

Also remove dependency on case crate now that it is no longer needed.

### CODE REVIEW

**Comment by EPashkin** [comment]
IMHO very good idea, even if it produces big changes.
Need rebase to solve merge conflict.

cc @GuillaumeGomez, @sdroege and @antoyo

**Comment by sdroege** [comment]
Seems good to me but if we change this let's please follow what is done in C a bit closer. It's `io_stream`, `im_context`, `uri_handler`, `unix_fd_list`. DBus is the odd one here with `GDbus` but `g_dbus` instead of `g_d_bus`

**Comment by tmiasko** [comment]
In this case, some further ideas:

1. Insert underscore in-between characters when going from lowercase to uppercase.
2. Version 1, but also insert underscore in-between second last and last
   uppercase character when going from sequence of three or more uppercase
   characters to lowercase.

Version 1 is what was proposed first, version 2 is some further refinement of
what I think @sdroege had in mind. The part "three or more uppercase characters"
is intended to avoid the case of single letter delimited with underscores.
If this don't feel to special casey to you, I would propose version 2.

**Comment by sdroege** [comment]
Do we have other examples of two uppercase characters in a row, other than `DBus`?

**Comment by tmiasko** [comment]
In trailing position: SoupCookieJarDB

**Comment by sdroege** [comment]
That's `soup_cookie_jar_db`, all good then. 2) seems like a good approach

**Comment by tmiasko** [comment]
I pushed updated implementation. It includes some additional test cases that
you might find interesting, especially those from GStreamer plugins. I think it
does agreeable job there, even in cases where it doesn't match what is used in
C code exactly.

For the record, new comparison table:

Type name    | Old module name | New module name
-------------|-----------------|----------------
DBusMessage  | d_bus_message   | dbus_message
FileIOStream | file_i_o_stream | file_io_stream
IMContext    | i_m_context     | im_context
IOStream     | i_o_stream      | io_stream
URIHandler   | u_r_i_handler   | uri_handler
UnixFDList   | unix_f_d_list   | unix_fd_list

**Comment by sdroege** [comment]
Looks good to me :+1:

**Comment by sdroege** [comment]
I would prefer if we could get my glib/gio PRs merged before moving around all the files. The merge conflicts will be annoying to solve :)

**Comment by GuillaumeGomez** [comment]
Fine by me. :)

**Comment by EPashkin** [comment]
Affected crates: gtk, gio, gdk

**Pull request merged**
