### PR TITLE
Cleanup redundant field names in struct initialization.

### PR DESCRIPTION
**Pull request by tmiasko**

### CODE REVIEW

**Comment by EPashkin** [comment]
Thanks, I was planing do this after your PR merged.
Please, also change this
```
warning: it is more idiomatic to loop over references to containers instead of using explicit iteration methods
  --> src\custom_type_glib_priority.rs:47:20
   |
47 |         for par in func.parameters.iter_mut() {
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: to write this more concisely, try: `&mut func.parameters`
   |
   = note: #[warn(explicit_iter_loop)] on by default
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.187/index.html#explicit_iter_loop

warning: it is more idiomatic to loop over references to containers instead of using explicit iteration methods
  --> src\visitors.rs:11:22
   |
11 |         for type_ in self.types.iter_mut() {
   |                      ^^^^^^^^^^^^^^^^^^^^^ help: to write this more concisely, try: `&mut self.types`
   |
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.187/index.html#explicit_iter_loop

warning: it is more idiomatic to loop over references to containers instead of using explicit iteration methods
  --> src\visitors.rs:25:59
   |
25 |             Type::Class(ref mut class) => for function in class.functions.iter_mut() {
   |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: to write this more concisely, try: `&mut class.functions`
   |
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.187/index.html#explicit_iter_loop

warning: it is more idiomatic to loop over references to containers instead of using explicit iteration methods
  --> src\visitors.rs:30:67
   |
30 |             Type::Interface(ref mut interface) => for function in interface.functions.iter_mut() {
   |                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: to write this more concisely, try: `&mut interface.functions`
   |
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.187/index.html#explicit_iter_loop

warning: it is more idiomatic to loop over references to containers instead of using explicit iteration methods
  --> src\visitors.rs:35:61
   |
35 |             Type::Record(ref mut record) => for function in record.functions.iter_mut() {
   |                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: to write this more concisely, try: `&mut record.functions`
   |
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.187/index.html#explicit_iter_loop
```

**Comment by EPashkin** [comment]
Thanks, I will merge after CI passed.

**Comment by tmiasko** [comment]
FYI: The remaining warning about replacing end with end was fixed in clippy https://github.com/rust-lang-nursery/rust-clippy/pull/2507, but appear to be unreleased yet.

**Comment by EPashkin** [comment]
Yes, I just installed gir version of clippy, so I don't see this warning now.

**Comment by EPashkin** [comment]
@tmiasko Thanks again

**Pull request merged**
