### PR TITLE
Add generation `Char` and `UChar` parameters

### PR DESCRIPTION
**Pull request by EPashkin**
Based on idea of https://github.com/gtk-rs/glib/pull/248

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
It's ready now, no?

**Comment by EPashkin** [comment]
If I remember right after this merged, glib#248 need update.

**Comment by GuillaumeGomez** [comment]
Well why not. Do you want to handle the regen on `glib`?

**Comment by EPashkin** [comment]
Problem that glib's regen need done by @federicomenaquintero it his PR, as it added `glib::Char` type

**Comment by GuillaumeGomez** [comment]
OK. So except for this one (which can wait for next release), what else remains to be done before the release?

**Comment by EPashkin** [comment]
Maybe https://github.com/gtk-rs/glib/pull/261 too.

**Comment by GuillaumeGomez** [comment]
I'll ping them.

**Comment by EPashkin** [comment]
Seems all works fine, so I merge this.

**Pull request merged**
