### PR TITLE
Extend gpointer to void*

### LINKED ISSUE #856: `user_data` for callbacks being `<type name="gpointer" c:type="void*"/>` makes generation fail
Trying to generate high-level bindings for https://github.com/AravisProject/aravis/blob/master/src/arvcamera.h#L46 appears to fail due to `void*` being used instead of `gpointer`. Given the error raised, I assume this is due to https://github.com/gtk-rs/gir/blob/master/src/analysis/functions.rs#L904 .

Running `sed -i 's#void\*#gpointer#' Aravis-0.6.gir` works as a temporary workaround for this issue.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #856.

Waiting for @Ekleog to confirm it works in his case.

### CODE REVIEW

**Comment by EPashkin** [comment]
This PR comment many function in gio

**Comment by GuillaumeGomez** [comment]
That explains why gio compiled without issues... Not good.

**Comment by GuillaumeGomez** [comment]
No more commented issues.

**Comment by EPashkin** [comment]
@GuillaumeGomez Yes, now no unneeded changes in gtk-rs, Thanks

**Comment by Ekleog** [comment]
@GuillaumeGomez Can confirm it works, thanks!

**Pull request merged**
