### PR TITLE
Add doc for signals

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
I'll add for properties a bit later. I found a bug on rustdoc-stripper and I'm trying to fix it.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Part of #452.

**Comment by GuillaumeGomez** [comment]
cc @EPashkin

**Comment by EPashkin** [comment]
By description I thought that it still in WIP.
Thanks, @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
No, I interrupted the development to fix the issue on `rustdoc-stripper` (which has been fixed). I'm going to work on properties now.

**Pull request merged**
