### PR TITLE
Don't generate duplicated doc aliases

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
You can see the results there: https://github.com/gtk-rs/gtk3-rs/compare/master...GuillaumeGomez:regen?expand=1

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
that's actually an expected behaviour

**Comment by GuillaumeGomez** [comment]
Really? How so?

**Comment by bilelmoussaoui** [comment]
> Really? How so?

The doc alias allows search for the `connect_X` by typing the signal name or the property name

**Comment by GuillaumeGomez** [comment]
Yes, but here it is generated on both trait declaration and trait impl. It'll remain on trait declaration.

**Comment by bilelmoussaoui** [comment]
> Yes, but here it is generated on both trait declaration and trait impl. It'll remain on trait declaration.

Ah I see what you mean now. Never mind, i should have been more careful looking at the generated code

**Review by bilelmoussaoui — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
;)

Sending the regens!

**Pull request merged**
