### PR TITLE
Allow to ignore builders

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
IMHO better just add `options.ignored_builders`.
I don't like to add it to objects list directly.
@sdroege what you think about this?

**Comment by sdroege** [comment]
Needs to be added to the `README.md`

**Comment by sdroege** [comment]
>  @sdroege what you think about this?

See comments in the gtk PR, I think these are not actually needed and another change in gir would be needed instead.

But for this specific configuration, I would add it to the objects directly instead. It's a configuration for the object and not a global configuration.

**Comment by sdroege** [comment]
On the other hand, `builders` is a global list and not per object... so this would be consistent at least. I don't like `builders` to be global either, but I also don't use it in any of my crates

**Comment by GuillaumeGomez** [comment]
@EPashkin: so @sdroege suggested to remove the global builder list and instead add a `generate_builder` key to objects. What do you think about it? If we agree on this, I'll update this PR and make the change as well (and on the other repositories too).

**Comment by sdroege** [comment]
@GuillaumeGomez And to make the required changes smaller, maybe there could be a global option to create builders by default or to not create them. And then have a configuration to override that default per object?

**Comment by GuillaumeGomez** [comment]
Sure.

**Comment by EPashkin** [comment]
@GuillaumeGomez Ok, Lets change `generate_builder: Option<bool>` in `Gobject`,
and remove global list in future

**Comment by GuillaumeGomez** [comment]
Ok, I'll update this PR then.

**Comment by GuillaumeGomez** [comment]
I removed the global "generate_builders", I also took into account the "abstract" property. So if we all agree on this, I'll add documentation and update the repositories using "generate_builders" (only gtk as far as I can tell).

What do you think?

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks, all looks good

**Comment by GuillaumeGomez** [comment]
Arf, I didn't update documentation, I just wanted your opinion before merging. :laughing: Well, sending another PR quickly to fix this then!

**Pull request merged**
