### PR TITLE
Replace `once_cell` crate with `std::sync::OnceLock`

### PR DESCRIPTION
**Pull request by andy128k**
See also https://github.com/gtk-rs/gtk-rs-core/pull/1289

### CODE REVIEW

**Comment by andy128k** [comment]
Tests fail but when I checkout a version of `gir-files` before [this PR](https://github.com/gtk-rs/gir-files/pull/181) then they pass.

**Comment by bilelmoussaoui** [comment]
> Tests fail but when I checkout a version of `gir-files` before [this PR](https://github.com/gtk-rs/gir-files/pull/181) then they pass.

Should be fixed now

**Comment by andy128k** [comment]
Nope :( still fails

**Comment by bilelmoussaoui** [comment]
> Nope :( still fails

If you rebase, it should

**Review by sdroege — APPROVED** [review]

**Pull request merged**
