### PR TITLE
Fix variant doc generation

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
I realized afterwards that bitfields fields and enum variants were both `Member`, so it's not good for the second one. Maybe I should use the same code for bitfields as well? What do you think @EPashkin ?

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez Yes, please make bitfield same.
Also seems first `write_item_doc` can be made to function, but not sure that it make code clearer

**Comment by GuillaumeGomez** [comment]
Ok, I'll update the code quickly then!

**Comment by GuillaumeGomez** [comment]
@EPashkin I just realized: what do you mean by "`write_item_doc` can be made into function"? It's already a function, no?

**Comment by GuillaumeGomez** [comment]
In the meantime I applied the same change to the bitfield.

**Comment by EPashkin** [comment]
Calls `write_item_doc` in enum and bitfield are same and can be made into function that accepting: `doc`, `deprecated_version`, `doc_deprecated`

**Comment by GuillaumeGomez** [comment]
Oh I see. Indeed, I'm not sure it's very pertinent in here...

**Pull request merged**
