### PR TITLE
Allow overriding safety assertions for functions

### PR DESCRIPTION
**Pull request by sdroege**
Sometimes this is misdetected, see https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/issues/211

CC @EPashkin @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Please add documentation for it too (in the README file).

**Comment by sdroege** [comment]
> Please add documentation for it too (in the README file).

There is documentation for it :)

**Comment by GuillaumeGomez** [comment]
Oh indeed, sorry... I read but forgot it right away. 🤣

**Comment by EPashkin** [comment]
@sdroege Thanks

**Pull request merged**
