### PR TITLE
Revert "Remove adding callback_guard"

### PR DESCRIPTION
**Pull request by EPashkin**
This reverts commit a61ccc16be2e0add02ec7b7953f55ee04317cbf5.

Part of https://github.com/gtk-rs/glib/pull/250

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
Or better add config for this?

**Comment by GuillaumeGomez** [comment]
A default `cfg!` maybe?

**Comment by EPashkin** [comment]
@GuillaumeGomez Sorry, I don't understand.

**Comment by GuillaumeGomez** [comment]
I meant we added a new feature (in `Cargo.toml`) and it was a default one so it can be disabled. Better? :)

**Comment by EPashkin** [comment]
This way gir with from same commit can produce different result.
Not sure that it good idea.
Hm. I wrong, you can't change features in Cargo.toml without adding new commit (ignoring --no-default-features flag).
I don't see difference without this and just adding commit.
I meant adding option to `Gir.toml`.

**Comment by EPashkin** [comment]
.. but as "my" option in "Gir.toml" will be used only year or half maybe it unnecessary work.

**Comment by GuillaumeGomez** [comment]
I suppose... Let's just revert everything and avoid any unnecessary work.

**Comment by sdroege** [comment]
Yes, revert simply and then we revert the reverts in 1-2 months again.

**Pull request merged**
