### PR TITLE
use #[non_exhaustive] for generated enums

### LINKED ISSUE #884: Use #[non_exhaustive] for generated enums/flags
Stable since 1.40.

### PR DESCRIPTION
**Pull request by gdesmott**
Fix #884

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
A little explanation please? :)

**Comment by gdesmott** [comment]
What about this?

**Comment by GuillaumeGomez** [comment]
What's the point of this change?

**Comment by gdesmott** [comment]
See my updated commit message, I added some explanations.

**Comment by GuillaumeGomez** [comment]
Oh my bad, didn't see it. Looks good to me! :)

**Comment by EPashkin** [comment]
@gdesmott Thanks.
Please ping me when both CI pass.

**Comment by EPashkin** [comment]
Travis don't wait test your PRs again. Lets ignore it.

**Pull request merged**
