### PR TITLE
Deprecate functions and signals that deprecated by minimal version

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by EPashkin** [comment]
In https://github.com/gtk-rs/gtk/pull/326 I found new "bug" with pattern: some functions was wrongly ignored in "auto/widget.rs".
While I strongly don't like it, may be we need add "^" and "$" to pattern in code.
@gkoz, @GuillaumeGomez  what you think

**Comment by gkoz** [comment]
I agree that the lack of anchors is a hazard so it's safer to force-add them.

**Comment by GuillaumeGomez** [comment]
I agree with @gkoz.

**Comment by EPashkin** [comment]
Added anchors

**Comment by gkoz** [comment]
Thanks!

**Pull request merged**
