### PR TITLE
Don't use "ffi" suffix for sys crates

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/685

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
👍

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/glib/pull/470/files#r262832438 , otherwise looks all good to me.

**Comment by sdroege** [comment]
> See https://github.com/gtk-rs/glib/pull/470/files#r262832438 , otherwise looks all good to me.

I.e., I'd prefer if we also changed `sys` to `$crate_name_sys` so that no renaming at all is necessary anymore.

**Comment by EPashkin** [comment]
Ready for final check

**Comment by sdroege** [comment]
:+1:

**Pull request merged**
