### PR TITLE
#849 Add derive Default on Objects with parameters-less new functions

### PR DESCRIPTION
**Pull request by alex179ohm**
has been tested with the gtk updated master brach.
it changes from this previous generated code:
```rust
pub struct AboutDialogBuilder {
     artists: Option<Vec<String>>,
     authors: Option<Vec<String>>,
....
}
impl Default for AboutDialogBuilder {
      fn default() -> Self {
            Self::new()
      }
}
```
to:
```rust
#[derive(Default)]
pub struct AboutDialogBuilder {
     artists: Option<Vec<String>>,
     authors: Option<Vec<String>>,
....
}
```
maybe the `generate_default_for_new` function could be removed definitely, but is still used in `src/codegen/record.rs` in the `generate` function.

### CODE REVIEW

**Comment by EPashkin** [comment]
@alex179ohm Thanks.

@antoyo You agree with this change?

**Comment by antoyo** [comment]
@EPashkin: I'm not sure. Can we get a branch of `gtk-rs` generated with this?

**Comment by sdroege** [comment]
@EPashkin @antoyo @GuillaumeGomez Any reason why this wasn't merged yet?

**Comment by GuillaumeGomez** [comment]
No idea.

**Comment by antoyo** [comment]
Because some [stuff](https://github.com/gtk-rs/gtk/pull/905/files#diff-d96e500340aab6b0a9a9ed5c8853d7f4L46-L51) is removed in the generated code while it should not.

**Comment by sdroege** [comment]
I see, that's a problem indeed :) Thanks for writing a comment about that here. @alex179ohm can you fix that?

**Comment by EPashkin** [comment]
Added https://github.com/gtk-rs/gtk/pull/919 with only adding #[derive(Default)] IMHO it is enough,
will add gir PR if CI will be happy

**Comment by EPashkin** [comment]
Seems @alex179ohm missed that we wasn't have `impl Default for xxBuilder` at all, so only needed add one line to builder generator (I missed that too :wink: ).
But deriving `Default` and maybe `Clone` for all builders is IMHO good idea.
@sdroege, @GuillaumeGomez, @antoyo What you think about it?

**Comment by EPashkin** [comment]
Also we can replace https://github.com/gtk-rs/gir/blob/master/src/codegen/object.rs#L222-L234
with call of "xxxBulder::default()"`

**Comment by GuillaumeGomez** [comment]
For me it sounds good but I didn't work at all on builders so I prefer to let @sdroege and @antoyo answer on this.

**Comment by antoyo** [comment]
@EPashkin: Generating both derive is good.
Did you make a new PR?

**Comment by EPashkin** [comment]
@antoyo Yes, I added it, will merge after CI, then update gtk's

**Comment by EPashkin** [comment]
Closing in favor of #876

**Pull request closed without merging**
