### PR TITLE
Fix property parent check

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gtk/issues/608, #511

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
It only generated new property "alignment" for `GtkCellRendererText`
No other crates affected

**Comment by EPashkin** [comment]
Alternative solution: add `force=true` to property config, that disable dublicate check for it.

**Comment by EPashkin** [comment]
Second commit fix adding properties when same function already present in class.

Extra crates affected: gdk, sourceview

**Comment by GuillaumeGomez** [comment]
Looks good to me.

**Comment by sdroege** [comment]
👍 but I didn't check if this has any effect on GStreamer. I'll create an issue if it does, will check in the next days

**Pull request merged**
