### PR TITLE
WIP: Don't generate any but the main IsA<_> bound for extension traits

### PR DESCRIPTION
**Pull request by sdroege**
Closes https://github.com/gtk-rs/gir/issues/670

### CODE REVIEW

**Comment by EPashkin** [comment]
Result seems "hacky" (especially emit calls), but seems works good.
I don't see problem in gir code.

For reference there main changes:
```diff
-impl<O: IsA<AboutDialog> + IsA<glib::object::Object>> AboutDialogExt for O {
+impl<O: 'static + IsA<AboutDialog>> AboutDialogExt for O {
...
fn connect_activate_link<F: Fn(&Self, &str) -> Inhibit + 'static>(&self, f: F) -> SignalHandlerId {
         unsafe {
             let f: Box_<Box_<Fn(&Self, &str) -> Inhibit + 'static>> = Box_::new(Box_::new(f));
-            connect(self.to_glib_none().0, "activate-link",
+            connect(self.to_glib_none().0 as *mut _, "activate-link",
                 transmute(activate_link_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
         }
     }
...
-impl<O: IsA<ActionBar> + IsA<Container>> ActionBarExt for O {
+impl<O: 'static + IsA<ActionBar>> ActionBarExt for O {
...
     fn get_child_pack_type<T: IsA<Widget>>(&self, item: &T) -> PackType {
         unsafe {
             let mut value = Value::from_type(<PackType as StaticType>::static_type());
-            ffi::gtk_container_child_get_property(self.to_glib_none().0, item.to_glib_none().0, "pack-type".to_glib_none().0, value.to_glib_none_mut().0);
+            ffi::gtk_container_child_get_property(self.to_glib_none().0 as *mut ffi::GtkContainer, item.to_glib_none().0, "bpack-type\0".as_ptr() as *const _, value.to_glib_none_mut().0);
             value.get().unwrap()
         }
     }
...
     fn emit_escape(&self) {
-        let _ = self.emit("escape", &[]).unwrap();
+        let _ = unsafe { glib::Object::from_glib_borrow(self.to_glib_none().0 as *mut gobject_ffi::GObject).emit("escape", &[]).unwrap() };
     }
```

**Comment by sdroege** [comment]
The emit one will be nicer once I'm done with my next changes related to making `IsA` object-safe :)

**Comment by sdroege** [comment]
Ok then I clean this up later or some time this weekend and we can get it in for now to keep PRs small?

**Comment by EPashkin** [comment]
Yes, I was too hurry, sorry

**Comment by sdroege** [comment]
Not going to get to that today anymore, but I won't forget :) No problem, the code is doing the right thing it's just not the most beautiful code

**Comment by philn** [comment]
The generated code broke gstreamer-rs:
```
                                                                                                                                                                                                                  
error[E0282]: type annotations needed                                                                                                                                                                              
  --> gstreamer/src/auto/pad_template.rs:64:48                                                                                                                                                                     
   |                                                                                                                                                                                                               
64 |             gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bdirection\0".as_ptr() as *const _, value.to_glib_none_mut().0);                                          
   |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for `P`                                                                                   
   |                                                                                                                                                                                                               
   = note: type must be known at this point                                                                                                                                                                        
                                                                                                                                                                                                                   
error[E0282]: type annotations needed                                                                                                                                                                              
  --> gstreamer/src/auto/pad_template.rs:73:48                                                                                                                                                                     
   |                                                                                                                                                                                                               
73 |             gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bgtype\0".as_ptr() as *const _, value.to_glib_none_mut().0);                                              
   |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for `P`                                                                                   
   |                                                                                                                                                                                                               
   = note: type must be known at this point                  
```

And so on.

**Comment by sdroege** [comment]
Thanks, will check tomorrow. I know why this happens.

Should also completely disappear once I got my IsA refactoring done in the next days, so maybe waiting for that

**Comment by sdroege** [comment]
Basically we'll need to distinguish between being inside a trait impl or not. In trait impls we currently need the cast (and later something else), outside trait impls we need nothing and can directly call without a cast (and later something different for the calls that are for a parent type)

**Comment by EPashkin** [comment]
@sdroege For next PR: There wrong string "\"b{}\\0\" in src/codegen/property_body.rs, as result it tried work with child properties like "bexpand", "bfill" etc.

**Pull request merged**
