### PR TITLE
Use new glib::Object::new() syntax

### PR DESCRIPTION
**Pull request by ids1024**
Goes along with https://github.com/gtk-rs/gtk-rs/pull/219.

### CODE REVIEW

**Review by sdroege — APPROVED** [review]

**Comment by sdroege** [comment]
Also congratulations for getting PR #1024 :)

**Comment by GuillaumeGomez** [comment]
Are the failures expected? Because they seem legit, no?

**Comment by sdroege** [comment]
> Are the failures expected? Because they seem legit, no?

Yes, they need https://github.com/gtk-rs/gtk-rs/pull/219

**Comment by GuillaumeGomez** [comment]
Yes, just went through it, my bad! All good then, thanks!

**Pull request merged**
