### PR TITLE
Implement Default::default() for types with an empty constructor

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by EPashkin** [comment]
Maybe it unneeded buf can you make function with this?

**Comment by sdroege** [comment]
What function?

**Comment by EPashkin** [comment]
`fn declare_default(w: &mut Write, name: &str, functions: &[Function]) -> Result<()>`

**Comment by sdroege** [comment]
I see, makes sense. But where should I put it?

**Comment by sdroege** [comment]
Or you mean have the function twice in the two files?

**Comment by EPashkin** [comment]
To `general.rs`. One function 😉

**Comment by sdroege** [comment]
Done, thanks :)

**Comment by EPashkin** [comment]
@sdroege  Sorry, but can you change function name to `declare_default_from_new`

**Comment by sdroege** [comment]
Done

**Comment by EPashkin** [comment]
Thanks, @sdroege

**Pull request merged**
