### PR TITLE
Rename trait instead hiding, because your minimum version 1.31 don't …

### PR DESCRIPTION
**Pull request by EPashkin**
…support this

Part of #772

cc @GuillaumeGomez, @sdroege, @fkrull

### CODE REVIEW

**Comment by EPashkin** [comment]
Or "glib::object::ObjectType as ObjectType_" same as we do with box "use std::boxed::Box as Box_" ?

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/cairo/pull/260/files#r285871201 but works for me either way

**Comment by GuillaumeGomez** [comment]
I'd prefer "glib::object::ObjectType as ObjectType_". Just in case.

**Comment by EPashkin** [comment]
Ok, let it be `glib::object::ObjectType as ObjectType_`

**Pull request merged**
