### PR TITLE
Make cast generated enums to i32 non-scalar

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by EPashkin** [comment]
Its second part of `enum as i32`. See https://github.com/gtk-rs/examples/pull/88

**Comment by EPashkin** [comment]
AppVeyor build succeeded, @gkoz, please, merge this

**Comment by EPashkin** [comment]
Seems I missread matches, need more `(_)`

**Comment by EPashkin** [comment]
Or not?

**Comment by EPashkin** [comment]
I tried micro-optimisation on match.

**Comment by gkoz** [comment]
```
__Nonexhaustive(_) => panic!(),
```
This got me thinking: if we somehow get an unexpected variant from the library, should it be possible to pass it back unchanged? This would require complicated workarounds and making enums much fatter.

**Comment by EPashkin** [comment]
We can add flag for some enums, that convert it to `__Nonexhaustive(i32)` on `from_glib` and use it in `to_glib`

**Comment by EPashkin** [comment]
These enums still defended again direct converting, so I don't see any problems.

**Comment by gkoz** [comment]
Problem is we can't allow putting arbitrary `i32`s there and that's where complicated workarounds come in.

**Comment by EPashkin** [comment]
Sorry, don't understand :(

**Comment by gkoz** [comment]
Type safety and (likely memory safety too) require that a user can't just put any random value in that variant and also can't copy it from one enum into another, so it'd be along the lines of

```rust
pub struct Discriminant<T> {
    value: i32,
    _dummy: PhantomData<*const T>,
};

impl<T> struct Discriminant<T> {
    // there shouldn't be a safe way to put arbitrary discriminants into enums
    pub unsafe fn new(value: i32) -> Self {
        Discriminant {
            value: value,
            _dummy: PhantomData::new(),
        }
    }
}

pub enum Foo {
    Member1,
    Member2,
    Member3,
    __Nonexhaustive(Discriminant<Foo>),
}
```

This looks like it's not worth the trouble at this point.

**Comment by EPashkin** [comment]
IMHO it not much related to this PR ;)
Currently we safe from direct converting `enum <-> int` (not checked `int -> enum` but `FromPrimitive` trait seems discarded),
way make defence against `enum1 -> int -> enum2` you show IMHO not needed until some example arises.

**Pull request merged**
