### PR TITLE
Use GObject status when generating types

### PR DESCRIPTION
**Pull request by EPashkin**
Helper for https://github.com/gtk-rs/sys/issues/82

### CODE REVIEW

**Comment by EPashkin** [comment]
Main effect that it removes ignored constants instead comment it (https://github.com/gtk-rs/sys/pull/81),
I done this to be same for other types.

@sdroege It not cause problem in gstreamer?
cc @GuillaumeGomez too

**Comment by tmiasko** [comment]
Good idea. For consistency, I think we should consider types with manual
implementation as complete in type analysis. Then, we could just remove the
hack for GHookList and implement it outside the gir.

**Comment by EPashkin** [comment]
Overall is good idea, but `is_incomplete` then additional config parameter

**Comment by sdroege** [comment]
@EPashkin causes no changes at all in gstreamer

**Comment by EPashkin** [comment]
@sdroege thanks

**Comment by GuillaumeGomez** [comment]
Good for me as well. Thanks!

**Comment by EPashkin** [comment]
Then I merge this and update sys's PR

**Pull request merged**
