### PR TITLE
Fix async for boxed 

### PR DESCRIPTION
**Pull request by EPashkin**
Fix error, found in https://github.com/gtk-rs/sourceview/pull/35

cc @GuillaumeGomez, @sdroege 

PS. PR contains function extracting, so better check by commits

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Seems good for me, thanks a lot! (You even remove the `AsciiExt` unused import hehe!)

**Comment by sdroege** [comment]
As usual, how does the generated output look like afterwards? :) The PR in general looks fine

**Comment by EPashkin** [comment]
```diff
     #[cfg(any(feature = "v3_10", feature = "dox"))]
     fn backward_async<'a, P: Into<Option<&'a gio::Cancellable>>, Q: FnOnce(Result<(gtk::TextIter, gtk::TextIter), Error>) + Send + 'static>(&self, iter: &gtk::TextIter, cancellable: P, callback: Q) {
         let cancellable = cancellable.into();
         let cancellable = cancellable.to_glib_none();
         let user_data: Box<Box<Q>> = Box::new(Box::new(callback));
         unsafe extern "C" fn backward_async_trampoline<Q: FnOnce(Result<(gtk::TextIter, gtk::TextIter), Error>) + Send + 'static>(_source_object: *mut gobject_ffi::GObject, res: *mut gio_ffi::GAsyncResult, user_data: glib_ffi::gpointer)
         {
             callback_guard!();
             let mut error = ptr::null_mut();
             let mut match_start = gtk::TextIter::uninitialized();
             let mut match_end = gtk::TextIter::uninitialized();
-            let _ = ffi::gtk_source_search_context_backward_finish(_source_object as *mut _, res, &mut match_start, &mut match_end, &mut error);
-            let result = if error.is_null() { Ok((from_glib_none(match_start), from_glib_none(match_end))) } else { Err(from_glib_full(error)) };
+            let _ = ffi::gtk_source_search_context_backward_finish(_source_object as *mut _, res, match_start.to_glib_none_mut().0, match_end.to_glib_none_mut().0, &mut error);
+            let result = if error.is_null() { Ok((match_start, match_end)) } else { Err(from_glib_full(error)) };
             let callback: Box<Box<Q>> = Box::from_raw(user_data as *mut _);
             callback(result);
         }
         let callback = backward_async_trampoline::<Q>;
         unsafe {
             ffi::gtk_source_search_context_backward_async(self.to_glib_none().0, iter.to_glib_none().0, cancellable.0, Some(callback), Box::into_raw(user_data) as *mut _);
         }
     }
```

**Comment by sdroege** [comment]
👍

**Pull request merged**
