### PR TITLE
Use new Value::from_type() function for property getters

### PR DESCRIPTION
**Pull request by sdroege**
See https://github.com/gtk-rs/glib/pull/266

### CODE REVIEW

**Comment by EPashkin** [comment]
Please move https://github.com/gtk-rs/gir/blob/master/src/analysis/properties.rs#L83 to setter branch.
This don't change generated code object `glib_wrapper!` won't work without `use gobject_ffi;`,
but will make more clear that getter don't need it.

**Comment by sdroege** [comment]
Why? We need it for the setter *and* getter, or not? For calling `g_object_get_property()`. It should be in both branches, is that what you mean?

**Comment by EPashkin** [comment]
I meant to move it, was wrong that it not used :(
You right that safer add it to setter too.

**Comment by sdroege** [comment]
Done :)

**Comment by EPashkin** [comment]
Thanks

**Pull request merged**
