### PR TITLE
Marking Ignored types in one place

### LINKED ISSUE #201: Failure to ignore a class when passed in a container
```toml
[options]
girs_dir = "gir-files"
library = "Gio"
version = "2.0"
min_cfg_version = "2.32"
target_path = "."
work_mode = "normal"
external_libraries = [
    "GLib",
    "GObject",
]

generate = [
    "Gio.AppInfo",
    "Gio.AppLaunchContext",
]
```

```rust
    pub fn get_display<T: IsA<AppInfo>>(&self, info: &T, files: &[File]) -> Option<String> {
        unsafe {
            from_glib_full(ffi::g_app_launch_context_get_display(self.to_glib_none().0, info.to_glib_none().0, files.to_glib_none().0))
        }
    }
```

### PR DESCRIPTION
**Pull request by EPashkin**
Fix #201

### CODE REVIEW

**Comment by EPashkin** [comment]
May be we need add check for main objects: currently many functions uncommented by `Gir_Gtk.toml`:
gtk_builder_get_application
gtk_builder_set_application
gtk_file_chooser_add_filter
gtk_file_chooser_get_filter
gtk_file_chooser_remove_filter
gtk_file_chooser_set_filter
*gtk_icon_info_new_for_pixbuf
gtk_icon_info_load_symbolic_for_context
gtk_icon_info_load_symbolic_for_style
gtk_image_new_from_icon_set
gtk_image_get_icon_set
gtk_image_set_from_icon_set
gtk_search_bar_connect_entry
many gtk_text_buffer_*
gtk_text_iter_backward_to_tag_toggle
gtk_text_iter_begins_tag
gtk_tool_palette_get_drag_item
gtk_tool_palette_get_drag_target_group
gtk_tool_palette_get_drag_target_item
many gtk_tree_view_*

*due `implemented_in_main_namespace`

**Comment by gkoz** [comment]
Also in the gtk repo this change uncomments signatures with `Border`, `WidgetPath`.

**Comment by EPashkin** [comment]
So what better: ignore by function or add extra check for ignored (in this case we needed add many manual objects) ?

**Comment by gkoz** [comment]
I'm still not clear which manual objects we'd need to add.

**Comment by EPashkin** [comment]
After add fast check these objects (without Gtk. prefix) from first 15 auto files:
License
DialogFlags
ArrowType
ShadowType
BaselinePosition
Orientation
PackType
PositionType
ReliefStyle
ButtonBoxStyle

**Comment by gkoz** [comment]
So, enums and bitfields? It's currently reasonable to assume they are defined, we just reexport them from sys crates. Other types not so much.

**Comment by EPashkin** [comment]
Sorry, don't understand what your decide.

**Comment by gkoz** [comment]
It's correct to comment out uses of `Application`, `File`, `Settings` classes, `Border` and `WidgetPath` records, which have 'ignored' status because they really are absent.
The status of enums and bitfields either shouldn't matter or should be initialized to be manual, because listing them in the config seems pointless.

**Comment by EPashkin** [comment]
Removed last commit, so wrongly uncommitted functions need to be ignored or some objects added to generation

**Comment by gkoz** [comment]
Not too happy about introducing a regression. I'll think more on how to fix this tomorrow.

**Comment by EPashkin** [comment]
Closed in favor #205

**Pull request closed without merging**
