### PR TITLE
Update various dependencies to their latest versions

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by EPashkin** [comment]
Bad that appveyor still have `mingw-w64-i686-libgit2-0.24.0-1` instead of `mingw-w64-i686-libgit2-0.26.0-1`

**Comment by sdroege** [comment]
What does that mean? We can't update because appveyor is old? :)

**Comment by EPashkin** [comment]
Yes 😢 
At minimum we need lock git2 to 0.6.6 until appveyour updated.

**Comment by sdroege** [comment]
Ah good old windows preventing progress everywhere else again :) I assume we don't know when or if appveyor will be updated?

**Comment by EPashkin** [comment]
Yes 😭

**Comment by sdroege** [comment]
Ok so what do you suggest? Update everything except for git2?

**Comment by EPashkin** [comment]
Yes, maybe only add comment to git2 about appveyor

**Comment by sdroege** [comment]
Done

**Comment by EPashkin** [comment]
Thanks, just waiting CI

**Pull request merged**
