### PR TITLE
Generate correctly when mutable reference into Into

### LINKED ISSUE #382: The Into trait doesn't take into account if the variable is mutable
For example, when I generated for GtkSourceView, I got the following function:

```rust
fn create_context<'a, P: Into<Option<&'a gtk::TextIter>>>(&self, position: P) -> Option<CompletionContext> {
    let position = position.into();
    let position = position.to_glib_none_mut();
    unsafe {
        from_glib_none(ffi::gtk_source_completion_create_context(self.to_glib_none().0, position.0))
    }
}
```

However, the good header is:

```rust
fn create_context<'a, P: Into<Option<&'a mut gtk::TextIter>>>(&self, position: P) -> Option<CompletionContext> {
```

So `position` needs to be `&mut` instead of just `&`.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #382.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
cc @EPashkin

**Comment by EPashkin** [comment]
I already commented in https://github.com/gtk-rs/sourceview/pull/7.
Maybe I was wrong, but currently I don't see usage of this PR.

**Comment by GuillaumeGomez** [comment]
For sourceview, the problem can be overlook but more globally, this addresses potential future issues: if the wrapped type should be a mutable reference, actually, it isn't generated as a mutable one.

**Comment by EPashkin** [comment]
I remember only 2 possibilities for optional for mutable reference:
1) is "out" param, we handle this by always supplying value,
2) "inout" params, we currently handle it for simply types (Ex. gtk_editable_insert_text, as nonoptional)
In gtk optional inouts only gtk_init_*, we handle it manually or ignore.
In gdk: gdk_inits (same as gtk)
In glib: g_prefix_error (ignored)
In pango: pango_matrix_transform_pixel_rectangle (manual, as nonoptional) and pango_matrix_transform_rectangle (same)

**Comment by GuillaumeGomez** [comment]
So possibilities exist! :D

**Comment by EPashkin** [comment]
I don't see where it can be legally applied.
Only last possibilities in pango but from docs I don't see how it can be used without `rect`.

**Comment by GuillaumeGomez** [comment]
Well, I'll let you decide. Just close it if you really don't see it useful. ;)

**Comment by EPashkin** [comment]
@GuillaumeGomez, Sorry, but I don't see application of this PR in gtk-rs crates, so I close it.

**Pull request closed without merging**
