### PR TITLE
Fix invalid import add

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/gtk-rs/gtk/issues/872
Fixes https://github.com/gtk-rs/gir/issues/735

cc @sdroege @EPashkin

### CODE REVIEW

**Comment by sdroege** [comment]
That's covering all of https://github.com/gtk-rs/gir/issues/735 ?

**Comment by GuillaumeGomez** [comment]
I didn't check on gstreamer. I doubt it'd work as is though. I can extend it if you want.

**Comment by sdroege** [comment]
Please do, would be nice to get rid of all those unused `GString` imports

**Comment by EPashkin** [comment]
@GuillaumeGomez You don't know which function added this import in calendar?
I don't see any function with string :(
I worry that we don't add import "String" in some cases (I not found that case in gtk-rs).

**Comment by GuillaumeGomez** [comment]
Ok, extended it a bit. Doesn't have warning on `gstreamer-editing-services` anymore.

@EPashkin I'm removing the imports from the callbacks only so that should be pretty accurate.

**Comment by EPashkin** [comment]
@GuillaumeGomez Now I understand that, thanks.

**Comment by EPashkin** [comment]
Last change broke gio's g_settings_schema_source_list_schemas

**Comment by GuillaumeGomez** [comment]
Interesting! I'll take a look.

**Comment by GuillaumeGomez** [comment]
It now works on gio as well. :)

**Comment by EPashkin** [comment]
@GuillaumeGomez Yes, not only needed changes. Thanks.

**Comment by EPashkin** [comment]
* now only needed changes

**Comment by EPashkin** [comment]
Lets merge

**Pull request merged**
