### PR TITLE
Fix clippy warnings about passing short and Copy arguments by reference

### PR DESCRIPTION
**Pull request by EPashkin**
See https://rust-lang-nursery.github.io/rust-clippy/v0.0.209/index.html#trivially_copy_pass_by_ref

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez Changes is trivial so I merge when CI passed

**Comment by sdroege** [comment]
Sound good

**Comment by EPashkin** [comment]
Seems travis broke all nighly rust, I emailed its to travis support, they are working on this

**Comment by GuillaumeGomez** [comment]
That's weird... Well, I let you handle the merge in any case. :)

**Comment by sdroege** [comment]
That's probably https://github.com/rust-lang/rust/issues/51699

**Comment by EPashkin** [comment]
@sdroege Thanks for find it.

**Pull request merged**
