### PR TITLE
Add support for `libc::time_t` and related types

### PR DESCRIPTION
**Pull request by sdroege**
Allowed since https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3967.

Fixes https://github.com/gtk-rs/gir/issues/1559

### CODE REVIEW

**Comment by sdroege** [comment]
I'm not sure why but this breaks generation of safe bindings in unexpected ways

```diff
-#[doc(alias = "g_get_real_name")]
-#[doc(alias = "get_real_name")]
-pub fn real_name() -> std::ffi::OsString {
-    unsafe { from_glib_none(ffi::g_get_real_name()) }
-}
+//#[doc(alias = "g_get_real_name")]
+//#[doc(alias = "get_real_name")]
+//pub fn real_name() -> /*Unimplemented*/Basic: TimeT {
+//    unsafe { TODO: call ffi:g_get_real_name() }
+//}
```

For some reason `OsStr` and related are all mapped to `TimeT` now.

**Comment by sdroege** [comment]
Ah, because we hardcode the `tid`s in `src/library.rs` :roll_eyes:

**Comment by sdroege** [comment]
Has some pending problems in https://gitlab.gnome.org/GNOME/glib/-/issues/3311 but from our side this "works" from what I can see.

**Comment by sdroege** [comment]
@werdahias note that this just makes it "someone else's" problem, i.e. yours and somehow magically getting the correct type mappings in the `libc` crate.

**Comment by sdroege** [comment]
@bilelmoussaoui What should we do about this? IMHO ready to be merged

**Review by bilelmoussaoui — APPROVED** [review]

**Pull request merged**
