### PR TITLE
Do not pass $rust_class_name to glib_wrapper!

### PR DESCRIPTION
**Pull request by ids1024**
This is possible due to https://github.com/gtk-rs/gtk-rs/pull/10.

Regenerating the gtk-rs bindings and compiling it seems to work with the current changes there in https://github.com/gtk-rs/gtk-rs/pull/11.

### CODE REVIEW

**Review by sdroege — APPROVED** [review]

**Comment by sdroege** [comment]
Looks good to me, thanks! Let's get this in after gtk-rs/gtk-rs#11 is out of the way

**Comment by sdroege** [comment]
@GuillaumeGomez Good to go for you? CI needs some kicking, then it's probably fine.

**Comment by GuillaumeGomez** [comment]
Code looks good, CI results a lot less.

**Comment by sdroege** [comment]
> Code looks good, CI results a lot less.

If you restart the CI it should be green. That's gtk-rs/gtk-rs#11.

**Comment by sdroege** [comment]
Oh I have permissions for that too... restarted :)

**Comment by sdroege** [comment]
No, the CI is very unhappy. But already is before this PR :facepalm:

**Comment by sdroege** [comment]
Now the CI should be green except for Windows. Let's see

**Comment by sdroege** [comment]
So it seems, let's get it in then! Thanks for your patience :)

**Pull request merged**
