### PR TITLE
Fix borrowed_box clippy warning in generated trampoline code

### PR DESCRIPTION
**Pull request by sdroege**
https://github.com/rust-lang-nursery/rust-clippy/wiki#borrowed_box

### CODE REVIEW

**Comment by sdroege** [comment]
It also complains about https://github.com/rust-lang-nursery/rust-clippy/wiki#transmute_ptr_to_ref but this seems non-trivial to fix. E.g. in one of my examples this would become the following instead of a simple `transmute`. I'd ignore that warning :)

```Rust
&*(func as *const &for<'r, 'r, 'r> std::ops::Fn(&'r auto::pad::Pad, &'r mut pad::PadProbeInfo<'r>) -> auto::enums::PadProbeReturn + std::marker::Sync + std::marker::Send + 'static)
```

**Comment by EPashkin** [comment]
Thanks.
Affected crates  gio, gdk, gtk.
Gio, Gtk also need same replace in manual part.

**Comment by sdroege** [comment]
You agree that https://github.com/rust-lang-nursery/rust-clippy/wiki#transmute_ptr_to_ref is not worth the pain? Main problem here is updating all the references to `'r`

**Comment by EPashkin** [comment]
Yes, totally, As it need extra type definition for as conversion.

**Comment by sdroege** [comment]
Maybe there's a way how we can silence that one?

**Comment by sdroege** [comment]
Ah yes:
```Rust
#[cfg_attr(feature = "cargo-clippy", allow(transmute_ptr_to_ref))]
```

**Comment by sdroege** [comment]
I'll send a PR for adding that in the relevant places later

**Comment by EPashkin** [comment]
IMHO adding #cfg to each line/trampoline will make the code less understandable.
While adding `#![cfg_attr(feature = "cargo-clippy", allow(transmute_ptr_to_ref))]` will hide some other errors currently I prefer this way.
Also converting completely different types with `transmute` IMHO is better that ``

**Comment by EPashkin** [comment]
.. using `as` with some complex type.

**Pull request merged**
