### PR TITLE
Fix getting stable version

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by EPashkin** [comment]
"channel-rust-stable" was upgraded https://internals.rust-lang.org/t/future-updates-to-the-rustup-distribution-format/4196 and seems now its update stopped

**Comment by EPashkin** [comment]
@GuillaumeGomez Please, look at this fix.
Instead maybe we need start using rustup like https://github.com/japaric/rust-everywhere/blob/master/appveyor.yml#L39-L43?

**Comment by GuillaumeGomez** [comment]
The `rust-everywhere` version seems better, no?

**Comment by EPashkin** [comment]
Updated to rustup

**Comment by EPashkin** [comment]
As [gtk version](https://github.com/gtk-rs/gtk/pull/548) of this merged, I merge this too

**Pull request merged**
