### PR TITLE
Add options.split_build_rs

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/sys/pull/167#issuecomment-623858337

cc @sdroege , @GuillaumeGomez , @kinnison

### CODE REVIEW

**Comment by kinnison** [comment]
Can you show an example of how this would look in use?  I'm not as familiar with the Gir codebase.

**Comment by EPashkin** [comment]
https://github.com/gtk-rs/sys/pull/168

**Comment by sdroege** [comment]
This is great but can we also have it the other way around? :)

In `gstreamer-sys` I'm currently editing the generated `build.rs` for the version part specifically to add missing versions for making user's lives a bit easier: if no new API was added between GStreamer 1.14 and 1.16 in one library there would still be a `v1_16` feature so that users can simply select `v1_16` for all libraries without having to check for each of them if the feature actually exists. Or maybe for that I instead want a configuration option `add_empty_major_versions` to automate it?

**Comment by EPashkin** [comment]
@sdroege Yes IMHO you want `add_empty_major_versions` as currently we just check all item in namespace to get versions and your mode need change of this process.

**Comment by EPashkin** [comment]
Maybe it better be `include_versions_by_step="0.2"`

**Comment by EPashkin** [comment]
@sdroege if you want, I can add a `include_version_by_step` today.

**Comment by EPashkin** [comment]
.. or `add_empty_major_versions` with same functionality, but it will be buildin

**Comment by EPashkin** [comment]
.. only problem, how to detect max version if its not present in .gir

**Comment by sdroege** [comment]
That would have to be configured too, I guess. Would be great if you could add that :)

**Comment by EPashkin** [comment]
Added issue https://github.com/gtk-rs/gir/issues/916

**Pull request merged**
