### PR TITLE
Initial conversion to github actions

### PR DESCRIPTION
**Pull request by kinnison**
This PR converts CI on the `gir` repository to github actions.  This replaces appveyor and travis with Github's own CI system.

Roughly 10 minutes to run the workflow now.

### CODE REVIEW

**Comment by kinnison** [comment]
Note: appveyor will try to run (and probably fail) and actions won't run until the first time this is merged to master, I think to prevent people consuming random actions CPU until a project commits to using it.

You can see a run here - https://github.com/kinnison/gir/actions/runs/93936893

**Comment by EPashkin** [comment]
Looks good for me.
@sdroege, @GuillaumeGomez What you think?

**Comment by GuillaumeGomez** [comment]
Looks good to me as well. :)

**Comment by sdroege** [comment]
Let's get it in :)

**Comment by EPashkin** [comment]
@kinnison Thanks again

**Comment by kinnison** [comment]
@EPashkin Assuming you're the repo owner, you'll want to go and disable the appveyor hook now so that it doesn't keep trying to build

**Pull request merged**
