### PR TITLE
Add repositories urls in head comment

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin

### CODE REVIEW

**Comment by sdroege** [comment]
Good idea, just the name gir is a bit general

**Comment by EPashkin** [comment]
@sdroege Agree
@GuillaumeGomez Thanks

**Comment by EPashkin** [comment]
Hm, actually maybe this not so good idea:
at minimum someone can use custom fork of gir-files (maybe with complete different name)

**Comment by GuillaumeGomez** [comment]
Then they can update the url themselves? I'm not sure this is really an issue. Before we didn't indicate the repository at all. The situation is a bit better at least. :)

**Comment by EPashkin** [comment]
You mean they need fork and maintain fork of gir too? :wink:
If that problem really arises we can add options for gir-files link.

**Comment by GuillaumeGomez** [comment]
Yes, that's what I meant. And yes, but I'm not sure such a problem will ever appear...

**Comment by EPashkin** [comment]
IMHO as we don't include all .gir  in your gir-files (like https://github.com/gtk-rs/gir-files/pull/12),
creator wrapper for that .gir will need fork.

**Pull request merged**
