### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by EPashkin**
cc @GuillaumeGomez 

@sdroege Please test this on gstreamer, it must don't produce any difference

### CODE REVIEW

**Comment by sdroege** [comment]
I won't be able to test it until end of next week. Please try it yourself, thanks :)

**Comment by EPashkin** [comment]
@sdroege Regen for https://github.com/sdroege/gstreamer-rs show same changes as after your #441

**Comment by sdroege** [comment]
Good to go then IMHO :) but maybe explain a bit more what you actually did in the commit message

**Comment by EPashkin** [comment]
Not sure that extracting 2 functions `generate_trait` and `is_carray_with_direct_elements` need explanation, or you meant some other places (it just fixes that clippy suggest)?

**Comment by sdroege** [comment]
Ok, looked bigger on the phone :)

**Comment by EPashkin** [comment]
Ok, I merge this.

**Pull request merged**
