### PR TITLE
Fix doc generation

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
Hm, I thought that "gir PR incoming I assume!" means you don't have time for this and added  #744 too.

**Comment by EPashkin** [comment]
Your has lesser addition, but IMHO better use `is_totally_deprecated` as crate can have `deprecate_by_min_version = false`.
Whose PR will be main and changed?

**Comment by GuillaumeGomez** [comment]
Ah crap. No, it litteraly meant that I was about to write a PR for it. ;)

**Comment by GuillaumeGomez** [comment]
Well, yours is more complete so I'll close this one.

**Pull request closed without merging**
